### ISSUE TITLE
Thread death in iothread-# threads

### ISSUE THREAD

**Issue by cystek** [zeromq/jeromq#328] opened 2016-02-17 21:50 UTC
I've been experiencing thread death in the iothread-# threads. It is very intermittent, but every so often a number of them will throw the following exception and die (until there are no more iothreads left to process request in which case ZMQ hangs.

zmq.ZError$IOException: java.io.IOException: Broken pipe
        at zmq.Signaler.send(Signaler.java:125)
        at zmq.Mailbox.send(Mailbox.java:85)
        at zmq.Ctx.sendCommand(Ctx.java:403)
        at zmq.ZObject.sendCommand(ZObject.java:362)
        at zmq.ZObject.sendPipeTermAck(ZObject.java:238)
        at zmq.Pipe.delimit(Pipe.java:513)
        at zmq.Pipe.read(Pipe.java:209)
        at zmq.SessionBase.pullMsg(SessionBase.java:191)
        at zmq.Dealer$DealerSession.pullMsg(Dealer.java:24)
        at zmq.V1Encoder.messageReady(V1Encoder.java:84)
        at zmq.V1Encoder.next(V1Encoder.java:60)
        at zmq.EncoderBase.getData(EncoderBase.java:78)
        at zmq.StreamEngine.outEvent(StreamEngine.java:369)
        at zmq.StreamEngine.activateOut(StreamEngine.java:444)
        at zmq.SessionBase.readActivated(SessionBase.java:295)
        at zmq.Dealer$DealerSession.readActivated(Dealer.java:24)
        at zmq.Pipe.processActivateRead(Pipe.java:290)
        at zmq.ZObject.processCommand(ZObject.java:57)
        at zmq.IOThread.inEvent(IOThread.java:93)
        at zmq.Poller.run(Poller.java:247)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Broken pipe
        at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
        at sun.nio.ch.FileDispatcherImpl.write(FileDispatcherImpl.java:60)
        at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
        at sun.nio.ch.IOUtil.write(IOUtil.java:65)
        at sun.nio.ch.SinkChannelImpl.write(SinkChannelImpl.java:167)
        at zmq.Signaler.send(Signaler.java:121)
        at zmq.Mailbox.send(Mailbox.java:85)
        at zmq.Ctx.sendCommand(Ctx.java:403)
        at zmq.ZObject.sendCommand(ZObject.java:362)
        at zmq.ZObject.sendPipeTermAck(ZObject.java:238)
        at zmq.Pipe.delimit(Pipe.java:513)
        at zmq.Pipe.read(Pipe.java:209)
        at zmq.SessionBase.pullMsg(SessionBase.java:191)
        at zmq.Dealer$DealerSession.pullMsg(Dealer.java:24)
        at zmq.V1Encoder.messageReady(V1Encoder.java:84)
        at zmq.V1Encoder.next(V1Encoder.java:60)
        at zmq.EncoderBase.getData(EncoderBase.java:78)
        at zmq.StreamEngine.outEvent(StreamEngine.java:369)
        at zmq.StreamEngine.activateOut(StreamEngine.java:444)
        at zmq.SessionBase.readActivated(SessionBase.java:295)
        at zmq.Dealer$DealerSession.readActivated(Dealer.java:24)
        at zmq.Pipe.processActivateRead(Pipe.java:290)
        at zmq.ZObject.processCommand(ZObject.java:57)
        at zmq.IOThread.inEvent(IOThread.java:93)
        at zmq.Poller.run(Poller.java:247)
        at java.lang.Thread.run(Thread.java:745)

Since they handle all communications, I don't think iothreads should be allowed to die (at least not without replacing them with a fresh thread). I tried a custom build of trunk where I catch the exception in Poller.run() and log the stack traces to know when this would have occurred and it does seem that the problem resolves itself afterwards, so that could potentially be a fix unless there is a better place along the stack to handle the exception.

**Comment by andreasweber** [comment] 2016-03-12 10:09
No comments on this? 
I ran in a similar problem with an IOException teminating the reaper thread. No more file handles were cleaned up afterwards and the system crashed. 
I totally agree with @cystek here: io-/reaper-threads shouldn't be allowed to die - or at least they should be replaced in that case.
(BTW, this seems to be related to #332.)

Would be nice to get some more opinions on this, and also some comments about @cystek's suggestion, or some more ideas for a workaround until it's solved.

**Comment by miniway** [comment] 2016-03-12 13:04
That's right io/reaper threads shouldn't be dead in the middle of processing. Also we need to find out what causes those thread to be dead to handle the situation better.

Do you have any reproducible test cases even though it happens rarely?

**Comment by andreasweber** [comment] 2016-03-12 14:48
Sorry, no reproducible test. It happens during cluster stability tests where we also kill some of our processes in between. So our assumption is, that a remote socket endpoint is killed during ZeroMQ communication which causes the Broken pipe IOException below. 

Here's a stack trace example:
<pre><code>
2016-03-11/23:05:39.438 [reaper-1                        ] ERROR server.NIOServerCnxnFactory
      - Thread Thread[reaper-1,10,main] died
zmq.ZError$IOException: java.io.IOException: Broken pipe
        at zmq.Signaler.send(Signaler.java:124)
        at zmq.Mailbox.send(Mailbox.java:85)
        at zmq.Ctx.sendCommand(Ctx.java:388)
        at zmq.ZObject.sendCommand(ZObject.java:362)
        at zmq.ZObject.sendPipeTermAck(ZObject.java:238)
        at zmq.Pipe.processPipeTermAck(Pipe.java:385)
        at zmq.ZObject.processCommand(ZObject.java:97)
        at zmq.SocketBase.processCommands(SocketBase.java:863)
        at zmq.SocketBase.inEvent(SocketBase.java:968)
        at zmq.Poller.run(Poller.java:247)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Broken pipe
        at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
        at sun.nio.ch.FileDispatcherImpl.write(FileDispatcherImpl.java:60)
        at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
        at sun.nio.ch.IOUtil.write(IOUtil.java:65)
        at sun.nio.ch.SinkChannelImpl.write(SinkChannelImpl.java:167)
        at zmq.Signaler.send(Signaler.java:121)
        ... 10 more 
</code></pre>

**Comment by miniway** [comment] 2016-03-16 00:33
Thanks for the information, We got some error report that 0.3.5 has a stability issue. Could you test with 0.3.4 to see if the same problem exists?

**Comment by cystek** [comment] 2016-03-31 18:27
I also don't have anything reproducible and it seems very random as to when it happens (application-wise at least, I'm not sure if there's a symptom on the network level). The exceptions do seem to come in batches where multiple different IO threads will throw the exception then things seem to fix themself, but before I added in the exception handling/ignoring in Poller.run() each thread throwing the exception would die, so basically the thread pool would continue to dwindle a few at a time until no threads were left.

Catching the exception in Poller.run() does have one drawback,though: if the receiving process has not yet done a bind when the requester starts an infinite loop of exceptions will start to be thrown. As I'm using IPC, this requires both services being stopped and restarted since the responder application won't bind to the port if the requester is already connected (I get an address in use exception). Perhaps only ignoring the exception if JMQ has properly started would be a fix for this (since JMQ seems to be a state machine under the hood). Here's the improper startup exception in case it's useful:

> java.nio.channels.CancelledKeyException
        at sun.nio.ch.SelectionKeyImpl.ensureValid(SelectionKeyImpl.java:73)
        at sun.nio.ch.SelectionKeyImpl.readyOps(SelectionKeyImpl.java:87)
        at java.nio.channels.SelectionKey.isWritable(SelectionKey.java:312)
        at zmq.Poller.run(Poller.java:255)
        at java.lang.Thread.run(Thread.java:745)

**Comment by andreasweber** [comment] 2016-04-11 14:53
In the meantime we had some other severe problems with jeromq 0.3.5, e.g. spinning reaper/io thread and spinning ZMQ.Poller threads. We tried with 0.3.4 and - as @miniway assumed - it was much better than with 0.3.5. So we decided to use a 0.3.4 with some patches/commits of 0.3.5 and it seems to be stable now, at least much more stable than 0.3.5.

**Comment by cystek** [comment] 2016-04-13 01:57
I tried with 0.3.4 and while the threads didn't die as with 0.3.5, after a while the connection would stop connecting and would trigger a timeout implemented by the code. I seem to remember encountering this in an earlier version (0.3.3 I think) which was the main reason I had looked to trying out 0.3.5 in the first place (hoping this issue had been resolved). Perhaps the stack trace of where the timeouts occur may be useful:

zmq.ZError$IOException: java.nio.channels.ClosedByInterruptException
	at zmq.Signaler.send(Signaler.java:108)
	at zmq.Mailbox.send(Mailbox.java:83)
	at zmq.Ctx.send_command(Ctx.java:356)
	at zmq.ZObject.send_command(ZObject.java:364)
	at zmq.ZObject.send_own(ZObject.java:180)
	at zmq.Own.launch_child(Own.java:128)
	at zmq.SocketBase.add_endpoint(SocketBase.java:528)
	at zmq.SocketBase.connect(SocketBase.java:519)
	at org.zeromq.ZMQ$Socket.connect(ZMQ.java:1156)
	...
Caused by: java.nio.channels.ClosedByInterruptException
	at java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:202)
	at sun.nio.ch.SinkChannelImpl.write(SinkChannelImpl.java:172)
	at zmq.Signaler.send(Signaler.java:106)
	... 49 more

**Comment by daveyarwood** [comment] 2017-10-05 03:46
I'm certain that at least some of these channel/selector-related issues have been fixed since this issue was filed. We need to reassess with the current state of JeroMQ.

@cystek @andreasweber Are you still having related issues on the latest version of JeroMQ?

**Comment by andreasweber** [comment] 2017-10-10 15:03
@daveyarwood  Ok, I will try latest release 0.4.2. But as I wrote before, there is no reliable way to reproduce the problem, so my feedback may take some time.

**Comment by daveyarwood** [comment] 2018-10-28 01:05
It's been almost 3 years since this issue was created, and we haven't had confirmation that the issue still persists with the latest release of JeroMQ.

Closing for now -- feel free to reopen if it is still an issue with the latest release.

**Closed by daveyarwood** 2018-10-28 01:05 UTC
Labels: old issue - possibly resolved
