### ISSUE TITLE
Upgrade 0.3.4 to 0.4.2 -> Windows running out of ports

### ISSUE THREAD

**Issue by andreasweber** [zeromq/jeromq#495] opened 2017-10-20 12:05 UTC
I just did an update from jeromq 0.3.4 to 0.4.2 to check whether stability problems #365 #328 have been gone.
But I run into a problem, that our software was running out of ports on a Windows 10 machine.

I tried to break it down and created a simple REQ-REP test that reproduces the problem. (see attached "OutOfPortsTest.java"). The test just exchanges a message between REQ <-> REP every second, where the REQ socket receives messages via polling. To show the problem, the test creates a new REQ socket and a new Poller instance for each request, the old REQ socket is unregistered and closed.

Some more analysis showed:
-  It seems that it has to do with Poller instance creation, resp. not freeing resources for Poller objects or registered sockets that are no longer used. When using only one Poller instance in the test, I can't reproduce the issue.
- It happens with a "TCP" connection as well as when using an "inproc" connection.
- It just happens with Windows. I couldn't reproduce the problem under Linux.

I also had a look in the heap dumps after 300 requests with the test - and the number of instances look like a memory leak:

0.3.4:
zmq.Req 1
zmq.Poller 2
zmq.Poller$PollSet 5
...

0.4.2:
zmq.socket.reqrep.Req 300
zmq.poll.Poller 2
zmq.poll.Poller$Handle 300  
...

To reproduce the issue just run the test and monitor the used ports, e.g. via netstat in a loop:
 `netstat -p TCP -n  | find /i "TCP" /c`

With jeromq-0.3.4 the number of used ports is increasing to some 400-500 and then the number stays more or less stable.
With jeromq-0.4.2 the number increases until after some thousands the system is running out of ports.

Any ideas?

[OutOfPortsTest.zip](https://github.com/zeromq/jeromq/files/1401827/OutOfPortsTest.zip)

**Comment by daveyarwood** [comment] 2017-10-20 13:44
Could this be because the context stores references to Selectors every time a poller is created, so that it can clean them up when the context is terminated? But in your example code, we aren't terminating the context until the very end. So, I suspect that the pollers are hanging around in memory.

I looked in the ZMQ.Poller class and I don't even see where we have a close method, so perhaps it would help if we added one? Looking at ZMQ.Socket for comparison, it looks like when it is closed/destroyed, a message is sent to the reaper thread that probably does some important stuff to assist with GC.

**Comment by fredoboulo** [comment] 2017-10-21 17:31
Releasing the resources of the Poller is definitely needed, at least for that use case (the problem is pointed by that use, but recreating a poller over and over should be discouraged according to me).
I'm working on Linux, so I do not have full visibility of the problem... I will provide a PR to close the poller, so we can advance further on the topic.
What I do not fully undestand yet, is why there are still instances of sockets and handles. They should normally be released after closing (asynchronously but still...). And they are on my machine: context keeps track of 2 sockets only, and handles of pollers are low.

**Comment by trevorbernard** [comment] 2017-11-09 13:31
@andreasweber Can you verify this is still an issue?

**Comment by andreasweber** [comment] 2017-11-16 09:49
Looks good!
When using current trunk code and closing the Poller instances in my code, the tcp port usage remains stable. 
Heap dump looks also fine, there seems to be no more leak.
So from my point of view, this issues can be closed.

**Closed** 2017-11-16 12:47 UTC
