### ISSUE TITLE
ZMQ.Poller seems to miss a constructor

### ISSUE THREAD

**Issue by Bastercall** [zeromq/jeromq#561] opened 2018-06-12 08:29 UTC
Hello I have a problem while declaring a new Poller. When I write `Poller items = new Poller (2);` an error occurs. When I open the code via intellij th following is shown:

```
public static class Poller implements Closeable
    {
        /**
         * These values can be ORed to specify what we want to poll for.
         */
        public static final int POLLIN  = zmq.ZMQ.ZMQ_POLLIN;
        public static final int POLLOUT = zmq.ZMQ.ZMQ_POLLOUT;
        public static final int POLLERR = zmq.ZMQ.ZMQ_POLLERR;

        private static final int SIZE_DEFAULT   = 32;
        private static final int SIZE_INCREMENT = 16;

        private final Selector selector;
        private final Context  context;

        private PollItem[] items;
        private int        next;
        private int        used;

        private long timeout;

        // When socket is removed from polling, store free slots here
        private LinkedList<Integer> freeSlots;

        /**
         * Class constructor.
         *
         * @param context
         *            a 0MQ context previously created.
         * @param size
         *            the number of Sockets this poller will contain.
         */
        protected Poller(Context context, int size)
        {
            assert (context != null);
            this.context = context;

            selector = context.selector();
            assert (selector != null);

            items = new PollItem[size];
            timeout = -1L;
            next = 0;

            freeSlots = new LinkedList<>();
        }

        /**
         * Class constructor.
         *
         * @param context
         *            a 0MQ context previously created.
         */
        protected Poller(Context context)
        {
            this(context, SIZE_DEFAULT);
        }

        @Override
        public void close()
        {
            context.close(selector);
        }

        /**
         * Register a Socket for polling on all events.
         *
         * @param socket
         *            the Socket we are registering.
         * @return the index identifying this Socket in the poll set.
         */
```

Is the constructor simply missing, or it is me doing something wrong?

**Comment by esahekmat** [comment] 2018-06-12 10:38
You should use poller() or poller(int size) methods on Context object to create a new Poller instance.

**Comment by fredoboulo** [comment] 2018-06-12 19:57
Previous constructor was removed because the poller needs a Selector to work, which was susceptible to cause resource leak.
You now create it with Context#poller() or ZContext#createPoller.

Closing the poller will release the Selector resource.

**Comment by trevorbernard** [comment] 2018-06-20 14:05
This is working as designed.

**Closed by trevorbernard** 2018-06-20 14:05 UTC
