### ISSUE TITLE
zmq.ZError$IOException: java.io.IOException: Too many open files

### ISSUE THREAD

**Issue by kmualem** [zeromq/jeromq#596] opened 2018-09-04 07:45 UTC
Hi Guys,

I saw some "Too many open files" issues and I'm wondering whether there is a problem with our code/approach or if this is a known issue that already fixed (or should be fixed)

We are using the latest version: 0.4.3
The scenario is that we have a web application (tomcat), we keep one ZContext instance and we use shadowZcontext for each socket that we open and inproc DEALER and ROUTER sockets.
For each inproc message, we are doing the following:
1. Create shadow context
2. Create inproc DEALER socket
3. the inproc ROUTER socket already exists in Reactor thread
4. send message
5. in finally, closing the socket.

`ZContext shadowZcontext = ZContext.shadow(zcontext);
Socket socket = getShadowContext().createSocket(ZMQ.DEALER);
socket.setLinger(0);
socket.connect('inproc://endpint');
socket.setSendTimeOut(0); 
socket.setReceiveTimeOut(0);
zmsg.send(socket);
// then in finally block
getShadowContext().destroySocket(socket);
shadowZcontext.destroy();
`

The OS is centos 7
The exception that we see is after some automation tests, not heavy requests at all...
"zmq.ZError$IOException: java.io.IOException: Too many open files"

We could increase the default limit for the number of open file descriptors (which is 4096), but we’d likely end up hitting the new limit eventually anyway if sockets aren’t being closed.

Can you please help? 

`

**Comment by fredoboulo** [comment] 2018-09-04 21:41
Constantly creating and destroying sockets is considered as an anti-pattern for ZMQ.

Apart from that, I tried that kind of code with latest SNAPSHOT and stopped it after 1 million iterations without any exception. It seems to be working as well with 0.4.3.

```
    @Test
    public void testCreateDestroy()
    {
        ZContext ctx = new ZContext();
        Socket socket = ctx.createSocket(ZMQ.ROUTER);
        socket.setReceiveTimeOut(1);
        socket.bind("inproc://endpint");
        ZMsg msg = new ZMsg();
        msg.add("hello");
        msg.add("world");

        try {
            for (int idx = 0; idx < 1_000_000_000; ++idx) {
                createDestroy(ctx, msg);

                if (idx % 1000 == 0) {
                    System.out.println(idx);
                }
                ZMsg.recvMsg(socket);
            }
        }
        finally {
            ctx.destroySocket(socket);
            ctx.close();
        }
    }

    private void createDestroy(ZContext ctx, ZMsg msg)
    {
        ZContext shadowZcontext = ZContext.shadow(ctx);
        Socket socket = shadowZcontext.createSocket(ZMQ.DEALER);
        try {
            socket.connect("inproc://endpint");
            socket.setSendTimeOut(0);
            socket.setReceiveTimeOut(0);
            msg.send(socket);
        }
        finally {
            shadowZcontext.destroySocket(socket);
            shadowZcontext.destroy();
        }
    }
```

The key to not hit the maximum number of sockets was in the binding side. Could you show the code of your ROUTER?

**Comment by kmualem** [comment] 2018-09-05 07:53
This is the code in the ROUTER side:

`
this.router = getzContext().createSocket(ZMQ.ROUTER);
this.router.setRouterMandatory(true);
this.router.bind('inproc://endpint');
`
In addition, we have a ZLoop and a PollItem (this.router, ZMQ.Poller.POLLIN); in order to handle on incoming events.

Re. the anti-patter, Do you have a suggestion on how to improve it? But, it seems from your tests that It should work fine ... so I'm not sure if this is really required.

What do you think ? 

Thanks a lot for your help!

**Comment by fredoboulo** [comment] 2018-09-05 20:55
You really have many short-lived threads that are sending one or few messages and then die? And they are out of your control?

Well, you can try some options: a pool of sockets, one socket with memory fence, one thread/socket with some queue of messages, ... I can only think of code involving java.util.concurrency at some point. That's a performance penalty, but when you are creating/destroying you are going through the configuration path which has horrible performance anyway.

One point. The code I posted is a bit biased, because it is receiving message as soon as it is sent before creating a new socket. With a ZLoop and parallel threading, things are not so nice...

As a side note, I'm not sure if you want bidirectional messaging, because you are only sending from one side. With unidirectional flow, PUSH-PULL might be more suited.

**Comment by kmualem** [comment] 2018-09-09 05:27
Generally, for most of the scenarios, I'm sending the ZMQ messages from one of the tomcat thread pool.. some apps use an external tomcat and others are sprint boot.

I can try re-using ZMQ sockets if this is a better approach... I will give it a try and check how it works.

Is there any performance concern while using Dealer / Router instead of PUSH-PULL?
In some cases, I do need bidirectional messaging because I'm waiting for an ACK from the router to the dealer sockets.

**Comment by fredoboulo** [comment] 2018-09-09 16:32
No concerns about performance that I am aware of between these 2 types. 

It's just that is the flow is unidirectional, I could have refined options to refactor your code.

Do not forget memory fences: one socket has be used in one thread only at a given point in time, including closing it. Sockets are not thread-safe. At all.

**Comment by dajkma** [comment] 2018-11-23 15:36
I have also received the "Too many open files" when using the last jeromq files in repository. 
The sockets will not be closed! 


The same code is working with jeromq 0.3.6 and 0.4.3.

```
zmq.ZError$IOException: java.io.IOException: Too many open files
        at zmq.Ctx.createSelector(Ctx.java:491)
        at zmq.Signaler.<init>(Signaler.java:54)
        at zmq.Mailbox.<init>(Mailbox.java:40)
        at zmq.SocketBase.<init>(SocketBase.java:119)
        at zmq.socket.reqrep.Dealer.<init>(Dealer.java:28)
        at zmq.socket.reqrep.Req.<init>(Req.java:44)
        at zmq.socket.Sockets$4.create(Sockets.java:50)
        at zmq.socket.Sockets.create(Sockets.java:139)
        at zmq.Ctx.createSocket(Ctx.java:396)
        at org.zeromq.ZMQ$Socket.<init>(ZMQ.java:776)
        at org.zeromq.ZMQ$Socket.<init>(ZMQ.java:762)
        at org.zeromq.ZMQ$Context.socket(ZMQ.java:590)
        at org.zeromq.ZMQ$Context.socket(ZMQ.java:596)
Caused by: java.io.IOException: Too many open files
        at sun.nio.ch.EPollArrayWrapper.epollCreate(Native Method)
        at sun.nio.ch.EPollArrayWrapper.<init>(EPollArrayWrapper.java:130)
        at sun.nio.ch.EPollSelectorImpl.<init>(EPollSelectorImpl.java:69)
        at sun.nio.ch.EPollSelectorProvider.openSelector(EPollSelectorProvider.java:36)
        at java.nio.channels.Selector.open(Selector.java:227)
        at zmq.Ctx.createSelector(Ctx.java:485)
        ... 14 more
```
My code (details removed):

```
      theContext  = ZMQ.context(1);
      thePoller   = theContext.poller(1);

      ZMQ.Socket socket = aContext.socket(ZMQ.REQ);
      socket.connect(getAddress());
      socket.setLinger(LINGER_MS);  
      thePoller.register(socket, ZMQ.Poller.POLLIN);

      ...
      socket.send(request);
      
      ...
      int rc = thePoller.poll(TIMEOUT_MS);
      ...
      if (thePoller.getItem(0) != null) {
          thePoller.unregister(socket);
      }
      
      socket.close();          
```
I have debugged: when closing the socket the call "cpipe.flush()" in "zmq.Mailbox" returns false.
I use Linux Debian and java 1.8.

**Comment by daveyarwood** [comment] 2018-11-23 18:40
Quoting @fredoboulo earlier in this thread:

> Constantly creating and destroying sockets is considered as an anti-pattern for ZMQ.
> 
> Apart from that, I tried that kind of code with latest SNAPSHOT and stopped it after 1 million iterations without any exception. It seems to be working as well with 0.4.3.

It seems to me that getting the "Too many files" exception is not an indication of a bug in JeroMQ, but rather an indication that you are using too many sockets in your architecture, and there is likely a better way to organize your code such that you can reuse the same socket to send numerous messages.

**Comment by daveyarwood** [comment] 2018-11-23 18:42
Closing this issue in light of the above, but happy to keep the conversation going re: recommended use of ZMQ.

**Closed by daveyarwood** 2018-11-23 18:42 UTC
Labels: more information needed

**Comment by ptwohig** [comment] 2019-05-15 01:23
> Constantly creating and destroying sockets is considered as an anti-pattern for ZMQ.

Here's the problem.  Lots of Java apps run in servlet containers where you have no reasonable control over the thread pool that's managed by the application container.  I know the guide has that trying to use synchronization primitives is like drunkards sharing a beer or whatever, but that falls apart when I have no control over the thread running my code.  I do trust that the developers at Jetty/Tomcat/WebLogic or whatever your container is have done their jobs properly and figured out how to make multi-threaded application work properly.

This presents the following issues:
- The sockets themselves don't control the state of the thread, therefore we have no way of knowing when a particular thread will exit. (eg Jetty may decide to just spin down the thread at any time)
- The Socket is implemented internally with what appears to be a bunch of ThreadLocal instances so there's no way for any outside thread to actually spin it down.

A few approaches to this problem:
- **Make Sockets Safely Transferrable between Threads**  That is, when a thread is done with a Socket, put it back in a queue for the next thread to use.  I vaguely recall that the ZMQ guide said that there's a safe way to transfer a socket between two threads provided two threads don't try to *use* the socket at the same time.  No such facility seems to exist in JeroMQ, that or I missed it.
- **Use a Separate Thread Pool** which just sits on one socket per thread and uses something like an ExecutorService ... of course that defeats the whole point of trying ot use ZMQ because we're spinning up extra threads just to make ZMQ happy.
- **Open/Close a Socket when needed.**  But this is an anti-pattern and seems to be the cause of this issue.
- **Implement inproc:// to be truly lightweight** using something like [PipedInputStream](https://docs.oracle.com/javase/7/docs/api/java/io/PipedInputStream.html) and [PipedOutputStream](https://docs.oracle.com/javase/7/docs/api/java/io/PipedOutputStream.html).  If you look in the code there, it's just some internal passing.  Handing a few kilobytes of RAM through the same process should not use the OS to do so, unless I'm missing something.  Why can't this happen in pure 100% Java in RAM?
