### ISSUE TITLE
Assertion error polling from inside a new thread.

### ISSUE THREAD

**Issue by lwhite1** [zeromq/jeromq#253] opened 2015-06-03 18:26 UTC
I have code that looks like this:

```
public void handleRequests() {
    ZMQ.Poller items = new ZMQ.Poller(1);
    items.register(clientEndpoint, ZMQ.Poller.POLLIN);
    while (!Thread.currentThread().isInterrupted()) {
        byte[] message;
        items.poll();  // this is the line that throws exception.
        if (items.pollin(0)) {
            message = clientEndpoint.recv(0);
        }
    }
}
```

It works fine when i call it directly:

```
    foo.handleRequests();
```

but it fails regularly with assertion errors if it is run in a new thread:

```
    final Runnable listener = worldviewServer::handleRequests;
    Executors.newSingleThreadExecutor().execute(listener);
```

The stack trace I get is shown below:

Exception in thread "pool-6-thread-1" java.lang.AssertionError
    at zmq.Mailbox.recv(Mailbox.java:113)
    at zmq.SocketBase.process_commands(SocketBase.java:820)
    at zmq.SocketBase.getsockopt(SocketBase.java:258)
    at zmq.PollItem.readyOps(PollItem.java:107)
    at zmq.ZMQ.zmq_poll(ZMQ.java:708)
    at zmq.ZMQ.zmq_poll(ZMQ.java:600)
    at org.zeromq.ZMQ$Poller.poll(ZMQ.java:1618)
    at org.zeromq.ZMQ$Poller.poll(ZMQ.java:1592)
    at com.tracelink.worldview.server.Head.handleRequests(Head.java:68)
    at com.tracelink.worldview.server.WorldviewServer.handleRequests(WorldviewServer.java:236)
    at com.tracelink.worldview.server.fsm.EnablingAction$$Lambda$12/404648734.run(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

I'm using Java 8 with JeroMQ 0.3.5-SNAPSHOT

**Comment by daveyarwood** [comment] 2016-09-08 03:09
I'm new to the codebase, but it seems like the assertion error is happening [here](https://github.com/zeromq/jeromq/blob/master/src/main/java/zmq/Mailbox.java#L115) because `cpipe.read()` is returning `null`. I don't really understand the code in [that class](https://github.com/zeromq/jeromq/blob/master/src/main/java/zmq/YPipe.java#L151-L153) yet, so I can't say definitively what the problem might be.

But for what it's worth, I have read that interacting with the same socket asynchronously from multiple threads can cause problems. The ZMQ guide seems to discourage it, and instead, recommends that you have a single thread that both receives and sends messages.

**Comment by daveyarwood** [comment] 2017-08-29 00:53
The codebase has changed a lot over the past 2 years since this issue has been filed. There is still [an assertion in Mailbox.recv](https://github.com/zeromq/jeromq/blob/master/src/main/java/zmq/Mailbox.java#L103-L104) that the result of `cpipe.read()` is not null (`cpipe` being a YPipe), so that part of the code is still roughly the same, but there could have been any number of commits in the last 2 years that may have fixed this issue. As such, closing the issue. Feel free to reopen if the problem is still observable in the latest stable release.

**Closed by daveyarwood** 2017-08-29 00:53 UTC
