### ISSUE TITLE
Test Hang With Maven

### ISSUE THREAD

**Issue by dubiousFrog** [zeromq/jeromq#816] opened 2020-05-19 19:52 UTC
Running 'mvn package' hangs at test 'org.zeromq.ReqRepTest

**Comment by fbacchella** [comment] 2020-05-19 19:54
On each run ?

**Comment by dubiousFrog** [comment] 2020-05-19 19:56
Yes, I have yet to have it complete.

**Comment by fbacchella** [comment] 2020-05-19 20:12
There is a one minute timeout in it. Did you wait that much ? Is that happening with a git checkout ?
I have tested run time and with 78 run, I got the following result, with current git code:

```
name,min,max,median,average,stddev
"org.zeromq.ReqRepTest.testDisconnectOnLargeMessageIssue334",0.985,1.8,1.285,1.34632467532,0.163242743444
"org.zeromq.ReqRepTest.testIssue532",2.06,2.756,2.288,2.31961038961,0.143655717209
"org.zeromq.ReqRepTest.testWaitForeverOnSignalerIssue303",4.136,5.071,4.536,4.53422077922,0.199961075652
```

**Comment by dubiousFrog** [comment] 2020-05-20 16:54
Still hangs. Note that I am trying to run 'mvn package' to produce .jar file.

**Comment by fbacchella** [comment] 2020-05-21 00:02
Without more details, we cannot help you.

**Comment by fbacchella** [comment] 2020-05-21 17:20
Should be fixed in 450d8fbaf96061129d02abeaaa6e5e4d0a2db9d5.

**Comment by dubiousFrog** [comment] 2020-05-21 18:03
no longer hangs, but does not build. Returns this output:

`[ERROR] Failures:
[ERROR] org.zeromq.TestEvents.testEventConnectRetried(org.zeromq.TestEvents)
[ERROR]   Run 1: TestEvents.testEventConnectRetried:85 No event was received
[ERROR]   Run 2: TestEvents.testEventConnectRetried:85 No event was received
[ERROR]   Run 3: TestEvents.testEventConnectRetried:85 No event was received
[ERROR]   Run 4: TestEvents.testEventConnectRetried:85 No event was received
[ERROR]   Run 5: TestEvents.testEventConnectRetried:85 No event was received
[ERROR]   Run 6: TestEvents.testEventConnectRetried:85 No event was received
[INFO]
[ERROR] Errors:
[ERROR] org.zeromq.ReqRepTest.testDisconnectOnLargeMessageIssue334(org.zeromq.ReqRepTest)
[ERROR]   Run 1: ReqRepTest.testDisconnectOnLargeMessageIssue334:247 » TestTimedOut test timed ...
[ERROR]   Run 2: ReqRepTest.testDisconnectOnLargeMessageIssue334:247 » TestTimedOut test timed ...
[ERROR]   Run 3: ReqRepTest.testDisconnectOnLargeMessageIssue334:205 OutOfMemory Java heap spac...
[ERROR]   Run 4: ReqRepTest.testDisconnectOnLargeMessageIssue334 » OutOfMemory Java heap space
[ERROR]   Run 5: ReqRepTest.testDisconnectOnLargeMessageIssue334 » OutOfMemory Java heap space
[ERROR]   Run 6: ReqRepTest.testDisconnectOnLargeMessageIssue334 » OutOfMemory Java heap space
[INFO]
[ERROR] zmq.PollTest.testPollUdp(zmq.PollTest)
[ERROR]   Run 1: PollTest.testPollUdp:100 » Bind Cannot assign requested address: connect
[ERROR]   Run 2: PollTest.testPollUdp:100 » Bind Cannot assign requested address: connect
[ERROR]   Run 3: PollTest.testPollUdp:100 » Bind Cannot assign requested address: connect
[ERROR]   Run 4: PollTest.testPollUdp:100 » Bind Cannot assign requested address: connect
[ERROR]   Run 5: PollTest.testPollUdp:100 » Bind Cannot assign requested address: connect
[ERROR]   Run 6: PollTest.testPollUdp:100 » Bind Cannot assign requested address: connect
[INFO]`

**Comment by dubiousFrog** [comment] 2020-05-21 18:04
No longer hangs on test, but does not build. Output error list and test failure:

[ERROR] Failures:
[ERROR] org.zeromq.TestEvents.testEventConnectRetried(org.zeromq.TestEvents)
[ERROR]   Run 1: TestEvents.testEventConnectRetried:85 No event was received
[ERROR]   Run 2: TestEvents.testEventConnectRetried:85 No event was received
[ERROR]   Run 3: TestEvents.testEventConnectRetried:85 No event was received
[ERROR]   Run 4: TestEvents.testEventConnectRetried:85 No event was received
[ERROR]   Run 5: TestEvents.testEventConnectRetried:85 No event was received
[ERROR]   Run 6: TestEvents.testEventConnectRetried:85 No event was received
[INFO]
[ERROR] Errors:
[ERROR] org.zeromq.ReqRepTest.testDisconnectOnLargeMessageIssue334(org.zeromq.ReqRepTest)
[ERROR]   Run 1: ReqRepTest.testDisconnectOnLargeMessageIssue334:247 » TestTimedOut test timed ...
[ERROR]   Run 2: ReqRepTest.testDisconnectOnLargeMessageIssue334:247 » TestTimedOut test timed ...
[ERROR]   Run 3: ReqRepTest.testDisconnectOnLargeMessageIssue334:205 OutOfMemory Java heap spac...
[ERROR]   Run 4: ReqRepTest.testDisconnectOnLargeMessageIssue334 » OutOfMemory Java heap space
[ERROR]   Run 5: ReqRepTest.testDisconnectOnLargeMessageIssue334 » OutOfMemory Java heap space
[ERROR]   Run 6: ReqRepTest.testDisconnectOnLargeMessageIssue334 » OutOfMemory Java heap space
[INFO]
[ERROR] zmq.PollTest.testPollUdp(zmq.PollTest)
[ERROR]   Run 1: PollTest.testPollUdp:100 » Bind Cannot assign requested address: connect
[ERROR]   Run 2: PollTest.testPollUdp:100 » Bind Cannot assign requested address: connect
[ERROR]   Run 3: PollTest.testPollUdp:100 » Bind Cannot assign requested address: connect
[ERROR]   Run 4: PollTest.testPollUdp:100 » Bind Cannot assign requested address: connect
[ERROR]   Run 5: PollTest.testPollUdp:100 » Bind Cannot assign requested address: connect
[ERROR]   Run 6: PollTest.testPollUdp:100 » Bind Cannot assign requested address: connect
[INFO]

**Comment by fbacchella** [comment] 2020-05-21 19:10
OutOfMemory Java heap.
That's a problem on your settings. Not a bug.

**Closed by fbacchella** 2020-05-21 19:10 UTC
