### ISSUE TITLE
Cannot get XPUB/XSUB properly working

### ISSUE THREAD

**Issue by soerenGer** [zeromq/jeromq#612] opened 2018-10-03 15:27 UTC
Hi,
I am relativly new to jeromq and currently trying to get something with multiple sub/pub's working, i.e. using the SXUB/XPUB solutions with an intermediary proxy. However I seem to be missing something completely, the attached example does not work properly. I would expect to see many ""msg receivd:..." flowing on the console, but the receiving side seems to be not working.
Threads are created, messages are sent and the return code of sending is "true", so that seems all good. However nothing happens on the receive side. I also checked with asynchronous polling, but that did not help either.
The XPUB/XSUB seems to be quite simple to use, however I seem to be missing something quite fundamental. An eye opener is highly welcome ,-)

Regards,
Sören

```java
package playground;

import java.util.concurrent.atomic.AtomicInteger;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.junit.Test;
import org.zeromq.ZContext;
import org.zeromq.ZMQ;
import org.zeromq.ZMQ.Socket;
import org.zeromq.ZMsg;

public class ZmqXpubXsubTester {

	Logger logger = LogManager.getLogger(ZmqXpubXsubTester.class);

	// Publishers *bind* to this socket, the SUB of the proxy
	static String XSUB_SOCKET = "tcp://localhost:8010";

	// Subscribers *connect* to this socket, the PUB of the proxy
	static String XPUB_SOCKET = "tcp://localhost:8011";

	static AtomicInteger sendNumber = new AtomicInteger();

	static AtomicInteger receiveNumber = new AtomicInteger();

	@Test
	public void testXpubXsub() throws Exception {

		//
		// PROXY
		//
		Runnable proxy = createProxy();
		Thread tProxy = new Thread(proxy);
		tProxy.setName("PROXY");
		tProxy.start();

		Thread.sleep(1000);

		//
		// Subscribers
		//
		for (int i = 0; i < 5; i++) {
			Thread tSubscriber = new Thread(createSubscriber());
			tSubscriber.setName("Subscriber-" + i);
			tSubscriber.start();

		}

		Thread.sleep(1000);

		//
		// Publishers
		//
		for (int i = 0; i < 5; i++) {
			Thread tPublisher = new Thread(createPublisher());
			tPublisher.setName("Publisher-" + i);
			tPublisher.start();

		}

		Thread.sleep(30000);
	}

	private Runnable createProxy() {
		Runnable proxy = new Runnable() {

			public void run() {

				// Create XPUB/XSUB Proxy
				ZContext ctx = new ZContext();
				Socket xpub = ctx.createSocket(ZMQ.XPUB);
				xpub.bind(XPUB_SOCKET);
				Socket xsub = ctx.createSocket(ZMQ.XSUB);
				xpub.bind(XSUB_SOCKET);

				// Call blocks
				ZMQ.proxy(xpub, xsub, null);
				logger.fatal("PROXY FINISHED !?");
			}
		};
		return proxy;
	}

	private Runnable createPublisher() {
		Runnable rv = new Runnable() {

			public void run() {
				try {
					ZContext ctx = new ZContext();
					Socket pub = ctx.createSocket(ZMQ.PUB);
					pub.connect(XSUB_SOCKET);
					logger.info("Publisher started");
					Thread.sleep(2000);

					for (int i = 0; i < 100; i++) {
						int m = sendNumber.incrementAndGet();
						ZMsg zmsg = ZMsg.newStringMsg("test", new String("Message Number " + m));
						boolean rv = zmsg.send(pub);
						logger.info("Sent msg #" + m + "; rv = " + rv);
						Thread.sleep(10);
					}
					pub.close();
					ctx.close();
				} catch (Exception e) {
					logger.error("Publisher startup with exception: " + e.getMessage(), e);
				}
			}
		};
		return rv;
	}

	private Runnable createSubscriber() {
		Runnable rv = new Runnable() {

			public void run() {
				try {
					ZContext ctx = new ZContext();
					Socket sub = ctx.createSocket(ZMQ.SUB);
					sub.connect(XPUB_SOCKET);
					sub.subscribe("test");
					sub.setRcvHWM(10000);
					logger.info("Subscriber started");
					while (true) {
						ZMsg message = ZMsg.recvMsg(sub);
						int m = receiveNumber.incrementAndGet();
						logger.info("msg receivd: " + new String(message.popString()) + ", counter now #" + m);
					}
				} catch (Exception e) {
					logger.error("Subscriber startup with exception: " + e.getMessage(), e);
				}
			}
		};
		return rv;
	}

}
```

**Comment by trevorbernard** [comment] 2018-10-05 01:17
Hi Sören, I would ask stackoverflow or the zeromq mailing list. I first would start with a PUB/SUB socket, get that working, then layer on the intermediate proxy. I will be closing this issue as it's not a bug.

**Closed by trevorbernard** 2018-10-05 01:17 UTC

**Comment by soerenGer** [comment] 2018-10-10 15:51
Homer says "Doh!"...it was a f*** typo. But hey, thanks for the hint with the mailing list, will try it next time!

**Comment by ruleil** [comment] 2021-08-20 02:35
> Hi,
> I am relativly new to jeromq and currently trying to get something with multiple sub/pub's working, i.e. using the SXUB/XPUB solutions with an intermediary proxy. However I seem to be missing something completely, the attached example does not work properly. I would expect to see many ""msg receivd:..." flowing on the console, but the receiving side seems to be not working.
> Threads are created, messages are sent and the return code of sending is "true", so that seems all good. However nothing happens on the receive side. I also checked with asynchronous polling, but that did not help either.
> The XPUB/XSUB seems to be quite simple to use, however I seem to be missing something quite fundamental. An eye opener is highly welcome ,-)
> 
> Regards,
> Sören
> 
> ```java
> package playground;
> 
> import java.util.concurrent.atomic.AtomicInteger;
> 
> import org.apache.logging.log4j.LogManager;
> import org.apache.logging.log4j.Logger;
> import org.junit.Test;
> import org.zeromq.ZContext;
> import org.zeromq.ZMQ;
> import org.zeromq.ZMQ.Socket;
> import org.zeromq.ZMsg;
> 
> public class ZmqXpubXsubTester {
> 
> 	Logger logger = LogManager.getLogger(ZmqXpubXsubTester.class);
> 
> 	// Publishers *bind* to this socket, the SUB of the proxy
> 	static String XSUB_SOCKET = "tcp://localhost:8010";
> 
> 	// Subscribers *connect* to this socket, the PUB of the proxy
> 	static String XPUB_SOCKET = "tcp://localhost:8011";
> 
> 	static AtomicInteger sendNumber = new AtomicInteger();
> 
> 	static AtomicInteger receiveNumber = new AtomicInteger();
> 
> 	@Test
> 	public void testXpubXsub() throws Exception {
> 
> 		//
> 		// PROXY
> 		//
> 		Runnable proxy = createProxy();
> 		Thread tProxy = new Thread(proxy);
> 		tProxy.setName("PROXY");
> 		tProxy.start();
> 
> 		Thread.sleep(1000);
> 
> 		//
> 		// Subscribers
> 		//
> 		for (int i = 0; i < 5; i++) {
> 			Thread tSubscriber = new Thread(createSubscriber());
> 			tSubscriber.setName("Subscriber-" + i);
> 			tSubscriber.start();
> 
> 		}
> 
> 		Thread.sleep(1000);
> 
> 		//
> 		// Publishers
> 		//
> 		for (int i = 0; i < 5; i++) {
> 			Thread tPublisher = new Thread(createPublisher());
> 			tPublisher.setName("Publisher-" + i);
> 			tPublisher.start();
> 
> 		}
> 
> 		Thread.sleep(30000);
> 	}
> 
> 	private Runnable createProxy() {
> 		Runnable proxy = new Runnable() {
> 
> 			public void run() {
> 
> 				// Create XPUB/XSUB Proxy
> 				ZContext ctx = new ZContext();
> 				Socket xpub = ctx.createSocket(ZMQ.XPUB);
> 				xpub.bind(XPUB_SOCKET);
> 				Socket xsub = ctx.createSocket(ZMQ.XSUB);
> 				xpub.bind(XSUB_SOCKET);
> 
> 				// Call blocks
> 				ZMQ.proxy(xpub, xsub, null);
> 				logger.fatal("PROXY FINISHED !?");
> 			}
> 		};
> 		return proxy;
> 	}
> 
> 	private Runnable createPublisher() {
> 		Runnable rv = new Runnable() {
> 
> 			public void run() {
> 				try {
> 					ZContext ctx = new ZContext();
> 					Socket pub = ctx.createSocket(ZMQ.PUB);
> 					pub.connect(XSUB_SOCKET);
> 					logger.info("Publisher started");
> 					Thread.sleep(2000);
> 
> 					for (int i = 0; i < 100; i++) {
> 						int m = sendNumber.incrementAndGet();
> 						ZMsg zmsg = ZMsg.newStringMsg("test", new String("Message Number " + m));
> 						boolean rv = zmsg.send(pub);
> 						logger.info("Sent msg #" + m + "; rv = " + rv);
> 						Thread.sleep(10);
> 					}
> 					pub.close();
> 					ctx.close();
> 				} catch (Exception e) {
> 					logger.error("Publisher startup with exception: " + e.getMessage(), e);
> 				}
> 			}
> 		};
> 		return rv;
> 	}
> 
> 	private Runnable createSubscriber() {
> 		Runnable rv = new Runnable() {
> 
> 			public void run() {
> 				try {
> 					ZContext ctx = new ZContext();
> 					Socket sub = ctx.createSocket(ZMQ.SUB);
> 					sub.connect(XPUB_SOCKET);
> 					sub.subscribe("test");
> 					sub.setRcvHWM(10000);
> 					logger.info("Subscriber started");
> 					while (true) {
> 						ZMsg message = ZMsg.recvMsg(sub);
> 						int m = receiveNumber.incrementAndGet();
> 						logger.info("msg receivd: " + new String(message.popString()) + ", counter now #" + m);
> 					}
> 				} catch (Exception e) {
> 					logger.error("Subscriber startup with exception: " + e.getMessage(), e);
> 				}
> 			}
> 		};
> 		return rv;
> 	}
> 
> }
> ```

Hi Sören

Did you get the XPub/XSub proxy work? I'm facing the same issue as you, the XSub not receiving any messages from connected publisers. I still trying to fix it...
