### ISSUE TITLE
Reaper thread silently dies when terminate is called when socket under heavy load

### ISSUE THREAD

**Issue by ppridge** [zeromq/jeromq#332] opened 2016-03-04 01:21 UTC
Hi,

We recently encountered a major issue when our system was under heavy load.   The heavy triggered a client heartbeat timeout, which in turn called Context.terminate for a socket that had a large backlog of data in transit.   This condition causes an IOException during the reaping process, which results in the reaper thread silently dying.  Once the reaper thread has died no socket resource will be cleaned up (closed) until the process is restarted.

I wrote a stress test with our system that reproduces this issue 100% of the time.  I do not have a stand alone case yet, as we are days away from a new release and don't have time to refactor yet.   So I will outline the test conditions.
1.  Setup pub/sub socket over tcp
2.  Start and  a very aggressive publisher
3.  30 seconds after the publisher starts call context.terminate on the publisher socket.
4.  jstack on the publisher process and grep for "reaper-1" thread.  In our test this thread no longer exists.

Here are the patches we applied locally to work around this bug.

Subject: JeroMq Proposed Fix

Here is the patch fixes for Jeromq 3.6.   Let me know if you have any objection to this.  All three production cases were type 1 exception.   After I was able to reproduce the issue, I wrote a stress tests that hammered this issue pretty hard.  This flushed out exception type 2, which I then added a strategic fix for.  
....

Exception Type 1 Fix (Zobject.java)

```java
protected void sendPipeTermAck(Pipe destination)
    {
      //TODO GRIMREAPER  Test this
      // Try to prevent reaper thread from dying due to IOException broken pipe, socket closed...
      // Don't know what is going to happen when PIPE_TERM_ACK is not received
      try {
        Command cmd = new Command(destination, Command.Type.PIPE_TERM_ACK);
        sendCommand(cmd);
      }
      catch (IOException e) {
        System.err.println("REAPER THREAD DEATH PREVENTION");
        e.printStackTrace();
      }
    }
```

# Exception Type 2 Fix (SocketBase.java)

```java
  @Override
    protected void processTerm(int linger)
    {
        //  Unregister all inproc endpoints associated with this socket.
        //  Doing this we make sure that no new pipes from other sockets (inproc)
        //  will be initiated.
        unregisterEndpoints(this);

    //TODO GRIMEREAPER
    int failCount = 0;
    //  Ask all attached pipes to terminate.
    for (int i = 0; i != pipes.size(); ++i) {
      try {
        pipes.get(i).terminate(false);
      }
      catch (Exception e) {
        //TODO GRIMREAPER
        // if can't terminate pipe then lessen the ack expectation
        failCount++;
        System.err.println("GRIM REAPER THREAD DEATH PREVENTION");
        e.printStackTrace();
      }
    }
    registerTermAcks(pipes.size() - failCount);

    //  Continue the termination process immediately.
    super.processTerm(linger);
}
```

# ExceptionType 1

```
Line 1737: 2016-03-02_23:52:49.066 [ERROR] [reaper-1] [zmq.ZObject] REAPER THREAD DEATH PREVENTION
                Line 1738: 2016-03-02_23:52:49.066 [ERROR] [reaper-1] [java.lang.Throwable] zmq.ZError$IOException: java.io.IOException: An established connection was aborted by the software in your host machine
                Line 1739: 2016-03-02_23:52:49.066 [ERROR] [reaper-1] [java.lang.Throwable]    at zmq.Signaler.send(Signaler.java:124)
                Line 1740: 2016-03-02_23:52:49.066 [ERROR] [reaper-1] [java.lang.Throwable]    at zmq.Mailbox.send(Mailbox.java:85)
                Line 1741: 2016-03-02_23:52:49.066 [ERROR] [reaper-1] [java.lang.Throwable]    at zmq.Ctx.sendCommand(Ctx.java:388)
                Line 1742: 2016-03-02_23:52:49.066 [ERROR] [reaper-1] [java.lang.Throwable]    at zmq.ZObject.sendCommand(ZObject.java:373)
                Line 1743: 2016-03-02_23:52:49.066 [ERROR] [reaper-1] [java.lang.Throwable]    at zmq.ZObject.sendPipeTermAck(ZObject.java:244)
                Line 1744: 2016-03-02_23:52:49.066 [ERROR] [reaper-1] [java.lang.Throwable]    at zmq.Pipe.processPipeTermAck(Pipe.java:385)
                Line 1745: 2016-03-02_23:52:49.066 [ERROR] [reaper-1] [java.lang.Throwable]    at zmq.ZObject.processCommand(ZObject.java:99)
                Line 1746: 2016-03-02_23:52:49.066 [ERROR] [reaper-1] [java.lang.Throwable]    at zmq.SocketBase.processCommands(SocketBase.java:831)
                Line 1747: 2016-03-02_23:52:49.066 [ERROR] [reaper-1] [java.lang.Throwable]    at zmq.SocketBase.inEvent(SocketBase.java:947)
                Line 1748: 2016-03-02_23:52:49.066 [ERROR] [reaper-1] [java.lang.Throwable]    at zmq.Poller.run(Poller.java:247)
                Line 1749: 2016-03-02_23:52:49.066 [ERROR] [reaper-1] [java.lang.Throwable]    at java.lang.Thread.run(Thread.java:745)
                Line 1750: 2016-03-02_23:52:49.066 [ERROR] [reaper-1] [java.lang.Throwable] Caused by: java.io.IOException: An established connection was aborted by the software in your host machine
                Line 1751: 2016-03-02_23:52:49.066 [ERROR] [reaper-1] [java.lang.Throwable]    at sun.nio.ch.SocketDispatcher.write0(Native Method)
                Line 1752: 2016-03-02_23:52:49.066 [ERROR] [reaper-1] [java.lang.Throwable]    at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:51)
                Line 1753: 2016-03-02_23:52:49.066 [ERROR] [reaper-1] [java.lang.Throwable]    at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
                Line 1754: 2016-03-02_23:52:49.066 [ERROR] [reaper-1] [java.lang.Throwable]    at sun.nio.ch.IOUtil.write(IOUtil.java:65)
                Line 1755: 2016-03-02_23:52:49.066 [ERROR] [reaper-1] [java.lang.Throwable]    at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:470)
                Line 1756: 2016-03-02_23:52:49.066 [ERROR] [reaper-1] [java.lang.Throwable]    at sun.nio.ch.SinkChannelImpl.write(SinkChannelImpl.java:114)
                Line 1757: 2016-03-02_23:52:49.066 [ERROR] [reaper-1] [java.lang.Throwable]    at zmq.Signaler.send(Signaler.java:121)
                Line 1758: 2016-03-02_23:52:49.066 [ERROR] [reaper-1] [java.lang.Throwable]    ... 10 more
```

# Exception Type 2

```
            Line 1762: 2016-03-02_23:52:49.144 [ERROR] [reaper-1] [zmq.SocketBase] GRIM REAPER THREAD DEATH PREVENTION
            Line 1763: 2016-03-02_23:52:49.144 [ERROR] [reaper-1] [java.lang.Throwable] zmq.ZError$IOException: java.io.IOException: An established connection was aborted by the software in your host machine
            Line 1764: 2016-03-02_23:52:49.144 [ERROR] [reaper-1] [java.lang.Throwable]    at zmq.Signaler.send(Signaler.java:124)
            Line 1765: 2016-03-02_23:52:49.144 [ERROR] [reaper-1] [java.lang.Throwable]    at zmq.Mailbox.send(Mailbox.java:85)
            Line 1766: 2016-03-02_23:52:49.144 [ERROR] [reaper-1] [java.lang.Throwable]    at zmq.Ctx.sendCommand(Ctx.java:388)
            Line 1767: 2016-03-02_23:52:49.144 [ERROR] [reaper-1] [java.lang.Throwable]    at zmq.ZObject.sendCommand(ZObject.java:373)
            Line 1768: 2016-03-02_23:52:49.144 [ERROR] [reaper-1] [java.lang.Throwable]    at zmq.ZObject.sendActivateRead(ZObject.java:216)
            Line 1769: 2016-03-02_23:52:49.144 [ERROR] [reaper-1] [java.lang.Throwable]    at zmq.Pipe.flush(Pipe.java:281)
            Line 1770: 2016-03-02_23:52:49.144 [ERROR] [reaper-1] [java.lang.Throwable]    at zmq.Pipe.terminate(Pipe.java:465)
            Line 1771: 2016-03-02_23:52:49.144 [ERROR] [reaper-1] [java.lang.Throwable]    at zmq.SocketBase.processTerm(SocketBase.java:873)
            Line 1772: 2016-03-02_23:52:49.144 [ERROR] [reaper-1] [java.lang.Throwable]    at zmq.Own.terminate(Own.java:191)
            Line 1773: 2016-03-02_23:52:49.144 [ERROR] [reaper-1] [java.lang.Throwable]    at zmq.SocketBase.startReaping(SocketBase.java:783)
            Line 1774: 2016-03-02_23:52:49.144 [ERROR] [reaper-1] [java.lang.Throwable]    at zmq.Reaper.processReap(Reaper.java:140)
            Line 1775: 2016-03-02_23:52:49.144 [ERROR] [reaper-1] [java.lang.Throwable]    at zmq.ZObject.processCommand(ZObject.java:115)
            Line 1776: 2016-03-02_23:52:49.144 [ERROR] [reaper-1] [java.lang.Throwable]    at zmq.Reaper.inEvent(Reaper.java:95)
            Line 1777: 2016-03-02_23:52:49.144 [ERROR] [reaper-1] [java.lang.Throwable]    at zmq.Poller.run(Poller.java:247)
            Line 1778: 2016-03-02_23:52:49.144 [ERROR] [reaper-1] [java.lang.Throwable]    at java.lang.Thread.run(Thread.java:745)
            Line 1779: 2016-03-02_23:52:49.144 [ERROR] [reaper-1] [java.lang.Throwable] Caused by: java.io.IOException: An established connection was aborted by the software in your host machine
            Line 1780: 2016-03-02_23:52:49.144 [ERROR] [reaper-1] [java.lang.Throwable]    at sun.nio.ch.SocketDispatcher.write0(Native Method)
            Line 1781: 2016-03-02_23:52:49.144 [ERROR] [reaper-1] [java.lang.Throwable]    at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:51)
            Line 1782: 2016-03-02_23:52:49.144 [ERROR] [reaper-1] [java.lang.Throwable]    at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
            Line 1783: 2016-03-02_23:52:49.144 [ERROR] [reaper-1] [java.lang.Throwable]    at sun.nio.ch.IOUtil.write(IOUtil.java:65)
            Line 1784: 2016-03-02_23:52:49.144 [ERROR] [reaper-1] [java.lang.Throwable]    at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:470)
            Line 1785: 2016-03-02_23:52:49.144 [ERROR] [reaper-1] [java.lang.Throwable]    at sun.nio.ch.SinkChannelImpl.write(SinkChannelImpl.java:114)
            Line 1786: 2016-03-02_23:52:49.144 [ERROR] [reaper-1] [java.lang.Throwable]    at zmq.Signaler.send(Signaler.java:121)
            Line 1787: 2016-03-02_23:52:49.144 [ERROR] [reaper-1] [java.lang.Throwable]    ... 14 more
```

_EDIT: code formatting - @daveyarwood_

**Comment by daveyarwood** [comment] 2016-11-07 05:19
@ppridge Thank you for your work on this! These stacktraces seem like good clues that may help us figure out the poller-related / ClosedChannelException / CPU usage problems that seem to have been introduced in 0.3.5.

**Comment by ppridge** [comment] 2016-11-12 23:52
Your welcome.  Although, the problem still exists the catches I put in allow our services to continue running,  where as before when the reaper thread died sockets would never be truly closed and released.
Please let me know if you make any progress.
Regards,
tom

**Comment by daveyarwood** [comment] 2018-01-15 03:18
Action needed:

- Write a test case based on the description of the test setup above.
- See if the original issue is still reproducible with the latest code from master branch.
- If the issue is still reproducible, see if the patches above fix it.

**Comment by KjellKod** [comment] 2018-01-23 21:23
Interested in this as well.   We see similar issues that seem to be introduced when we upgraded to 0.3.5

**Comment by daveyarwood** [comment] 2018-01-23 22:22
Worth noting: the latest release version of JeroMQ is 0.4.3. So, it may be worth confirming that the issues still exist in the latest version.

**Comment by javaJake** [comment] 2018-07-27 20:13
In response to https://github.com/zeromq/jeromq/issues/580 I rewrote the code that I was using to manage JeroMQ resources to ensure they're obviously single-threaded (i.e. it's hard to do "bad things").

I just wrote a simple test that writes as many messages as I/O writes, while on another thread draining messages as fast as I/O can read them. I use that to then test a thread-safe high-level close call I wrote, at which point I get a similar exception described in this issue. I'm using 0.4.3.

For a while I thought this was my own misuse of JeroMQ yet again, but I noticed that by simply throttling the messaging by a few milliseconds, failures completely vanished. I also tested by removing the close calls and just letting the send/receive threads run endlessly; they'd eventually fail on their own. That's what got me googling and got me to this thread. Therefore, feel free to question whether this stack proves the issue is still present in 0.4.3. I could just be bug-ridden. ;)

Example exception below:

```
zmq.ZError$IOException: java.io.IOException: An established connection was aborted by the software in your host machine
	at zmq.Signaler.send(Signaler.java:102)
	at zmq.Mailbox.send(Mailbox.java:71)
	at zmq.Ctx.sendCommand(Ctx.java:526)
	at zmq.ZObject.sendCommand(ZObject.java:382)
	at zmq.ZObject.sendPipeTermAck(ZObject.java:252)
	at zmq.pipe.Pipe.processDelimiter(Pipe.java:544)
	at zmq.pipe.Pipe.read(Pipe.java:229)
	at zmq.io.SessionBase.pullMsg(SessionBase.java:126)
	at zmq.io.StreamEngine$PullAndEncode.nextMsg(StreamEngine.java:156)
	at zmq.io.StreamEngine.outEvent(StreamEngine.java:633)
	at zmq.io.StreamEngine.restartOutput(StreamEngine.java:698)
	at zmq.io.SessionBase.readActivated(SessionBase.java:259)
	at zmq.pipe.Pipe.processActivateRead(Pipe.java:312)
	at zmq.ZObject.processCommand(ZObject.java:51)
	at zmq.Command.process(Command.java:75)
	at zmq.io.IOThread.inEvent(IOThread.java:80)
	at zmq.poll.Poller.run(Poller.java:273)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: An established connection was aborted by the software in your host machine
	at sun.nio.ch.SocketDispatcher.write0(Native Method)
	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:51)
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
	at sun.nio.ch.IOUtil.write(IOUtil.java:65)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471)
	at sun.nio.ch.SinkChannelImpl.write(SinkChannelImpl.java:114)
	at zmq.Signaler.send(Signaler.java:98)
```

**Comment by javaJake** [comment] 2018-07-27 21:12
You may be able to ignore my previous comment. I simplified my test further and eliminated the error entirely, even without the sleep.

**Comment by javaJake** [comment] 2018-07-27 21:41
Please ignore my messages. Something was interrupting my thread, which caused mayhem per usual.

**Comment by daveyarwood** [comment] 2018-10-28 01:08
If i'm understanding correctly, we haven't had confirmation that the issue still exists with 0.4.3, the latest release. I'm going to close this issue for now, but feel free to reopen if this issue persists with the latest release.

**Closed by daveyarwood** 2018-10-28 01:08 UTC
Labels: ready for action
