### ISSUE TITLE
Very slow to bind IPC socket

### ISSUE THREAD

**Issue by billchurch76** [zeromq/jeromq#284] opened 2015-09-01 15:10 UTC
I'm using a PUB/SUB scheme to transport some data on an Android device and have it set up to use IPC.  When bind is called it takes 10 seconds to complete the call every time.  If I change it to use TCP, it binds immediately.  I'd prefer using IPC, but the penalty seems highly unacceptable.

**Comment by miniway** [comment] 2015-09-01 19:56
For jeromq IPC is actually TCP with loopback address and a port as pure Java doesn't support unix socket. I think it takes time to get the loopback address from `InetAddress.getByName(null)`

Could make simple application than prints `InetAddress.getByName(null)` result only and check the execution time?

**Comment by billchurch76** [comment] 2015-09-02 19:59
The execution time on that call was effectively instantaneous.

**Comment by billchurch76** [comment] 2015-09-02 20:09
I don't know why ... and perhaps there's an issue with Android, my specific platform, or something in my implementation, but right now the bind is happening instantly, as one would expect it to.  I've changed nothing, though there may have been a reboot of the device.  There have been times when the bind will fail with an "Address already in use" exception thrown.  Perhaps whatever is getting me in that state is also causing the slow bind?

The sequence of events for my socket is essentially:

ZMQ.Socket socket = context.socket(ZMQ.PUB);
socket.setLinger(0);
socket.setSndHWM(0);
socket.setIPv4Only(false);
socket.bind("ipc://my-ipc-endpoint");

~ send some data ~

socket.close();
context.close();

**Comment by hintjens** [comment] 2015-09-02 20:17
Note the IPC endpoint maps to a real file. So it could be Android trying to
mount a non-existent file system and timing out. Try a directory that
exists, like ipc:///tmp/somefile.

**Comment by billchurch76** [comment] 2015-09-02 21:10
That's a very distinct possibility that I hadn't thought of, mostly because networking is not my forte in the least.  I created a new subfolder in a known structure and redirected both sides of the socket.  It's working just fine without any noticeable performance issues.  I'll consider this issue closed unless it rears up it's ugly head again.

Thank you both for your insight.

**Comment by miniway** [comment] 2015-09-02 21:15
For jzmq and c zeromq, IPC maps to a real file. But it's not for Jeromq due to a POJO limitation. Please refer https://github.com/zeromq/jeromq/blob/master/src/main/java/zmq/IpcAddress.java
it binds to a real tcp port.

**Comment by billchurch76** [comment] 2015-09-04 18:20
Ok, then I guess this is still an issue since Pieter's solution won't work. It's very maddening because while most of the time there's a 10 second delay (yes, always 10 seconds), there are times when it works very smoothly and quickly.

**Comment by Asmod4n** [comment] 2015-09-21 17:11
There is actually a way to use real unix sockets with java: https://github.com/jnr/jnr-unixsocket

**Comment by miniway** [comment] 2015-09-21 17:57
We tried to avoid using native interfaces. But jnr is much better than jni for the deployment perspective. Basically I'm very positive to use it as jnr-unixsocket is independent of a thirdparty library.

But we might need to make sure jnr-unixsocket works fine in Android devices.

**Comment by Asmod4n** [comment] 2015-09-21 18:29
One of the authors just said it should work, since jffi has a ARM binary, but it isn't tested.

**Comment by billchurch76** [comment] 2015-10-07 18:57
I'm really glad this has gotten the attention it has.  One thing, maybe related, to note is that recently I've been running into an issue where the IPC socket stood up as above fails to bind with exception:
"org.zeromq.ZMQException: Errno 48 : Address already in use"
This usually happens after my application has terminated abnormally, leaving the socket in a bad state.  Beyond rebooting the device, is there any way to recover from the exception?

**Comment by JonasVautherin** [comment] 2016-02-15 13:36
Is there any plan for integrating jnr to JeroMQ, or was it only a suggestion?

**Comment by msteinhoff** [comment] 2016-02-15 17:09
I'm not sure what using jnr in JeroMQ would buy us here. Afaics the goal of JeroMQ is to avoid native libraries. If one wants to use IPC, why not use jzmq directly?

**Comment by JonasVautherin** [comment] 2016-02-16 22:27
That was mainly curiosity, as I was not sure how to understand miniway's last message =).

**Comment by msteinhoff** [comment] 2016-02-16 23:16
Okay :)

If you are interested, [jni-ffr](https://github.com/jnr/jnr-ffi) looks like something worth to investigate as an alternative to the JNI bridge in jzmq. I don't know if it would work but if I unterstood things correctly, we could use it as a replacement for JNI and get a much more simplified build process.

Of course, such a jni-ffr bridge should provide equal functionality, equal or better performance and better maintainability compared to the current JNI bridge.

**Comment by hintjens** [comment] 2016-02-16 23:51
You might also enjoy the CZMQ and Zyre JNI bindings.

**Comment by msteinhoff** [comment] 2016-02-17 11:39
I'll have a look at it.

**Comment by msteinhoff** [comment] 2016-02-17 11:59
The CZMQ JNI bindings are very nice, I like its simplicity. Its time to use zproject in libzmq. :-)

**Comment by hintjens** [comment] 2016-02-17 13:37
Ah... an interesting idea. It might even be possible...

**Comment by daveyarwood** [comment] 2017-10-05 03:20
I agree with the comments above about JeroMQ having a goal of providing native dependency-free ZMQ in Java. 

@billchurch76: It's been over 2 years since this issue was created. I'm curious if it's still reproducible, or if we should close it?

**Comment by daveyarwood** [comment] 2018-10-28 00:43
There's been no activity on this issue in almost 3 years, and it's possible that the issue has resolved itself by now. Closing for now, feel free to reopen if the issue is still there with the latest version of JeroMQ.

**Closed by daveyarwood** 2018-10-28 00:43 UTC
Labels: old issue - possibly resolved
