### ISSUE TITLE
Router/Dealer message miss?

### ISSUE THREAD

**Issue by GazitGu** [zeromq/jeromq#381] opened 2016-11-11 12:41 UTC
Hi Jeromq team,

Thanks for your great work, i am using jeromq recently to build async server/client, but i found some data was missed when transfer, below classes can reproduce the issue, please correct me if i used wrong functions.

ZeroMQTransport.java

```java
package com.jeromq.test;

import java.nio.ByteBuffer;
import java.util.Queue;
import java.util.Random;
import java.util.concurrent.BlockingQueue;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.LinkedBlockingQueue;

import org.zeromq.ZContext;
import org.zeromq.ZFrame;
import org.zeromq.ZMQ;
import org.zeromq.ZMQ.PollItem;
import org.zeromq.ZMQ.Socket;
import org.zeromq.ZMsg;
import org.zeromq.ZThread;
import org.zeromq.ZThread.IAttachedRunnable;

public class ZeroMQTransport {
  private final ZContext context;
  private Socket socket;
  private Socket sendPipe;
  private Socket receivePipe;
  private final String addresses;
  private final int type;
  private final boolean bind;

  private MessageListener listener;

  private BlockingQueue<TaskMessage> outgoing = new LinkedBlockingQueue<TaskMessage>();
  private BlockingQueue<TaskMessage> incoming = new LinkedBlockingQueue<TaskMessage>();
  
  private final ExecutorService outgoingExecutorService = Executors.newSingleThreadExecutor();
  private final ExecutorService incomingExecutorService = Executors.newSingleThreadExecutor();

  public ZeroMQTransport(final ZContext context, final String addresses, int type, boolean bind) {
    this.context = context;
    this.type = type;
    this.addresses = addresses;
    this.bind = bind;
  }

  public void start() {
    outgoingExecutorService.execute(new Runnable() {
      public void run() {
        try {
          while(true){
            TaskMessage tm = outgoing.take();
            onOutgoingMessage(tm);
          }
        } catch (Exception e) {
          e.printStackTrace();
        }
      }
    });
    incomingExecutorService.execute(new Runnable() {
      public void run() {
        try {
          while(true){
            TaskMessage tm = incoming.take();
            if(listener!=null){
              listener.onMessage(tm);
            }
          }
        } catch (Exception e) {
          e.printStackTrace();
        }
      }
    });
    createSocket();
  }
  
  private void onOutgoingMessage(TaskMessage event) {
    try {
      if (type == ZMQ.ROUTER) {
        byte[] address = event.getSession();
        if (address != null) {
          sendPipe.send(address,ZFrame.REUSE + ZFrame.MORE);
        } else {
          System.out.println("Router send message but without session combined.");
          return;
        }
      }

      if (type == ZMQ.PUB) {
        sendPipe.sendMore(event.getSubject());
      }
      
      ByteBuffer buffer = event.getBuffer();
      byte[] b = new byte[buffer.remaining()];
      buffer.mark();
      buffer.get(b);
      buffer.reset();
      
      boolean bo = sendPipe.send(b, 0);
      if (!bo) {
        System.out.println("Received send failed.");
      } 
    } catch (Exception e) {
      e.printStackTrace();
    }
  }

  private class Sender implements IAttachedRunnable {

    private Socket receivePipe;
    private Random rand = new Random(System.nanoTime());

    public Sender() {

    }

    public Sender(Socket socket) {
      this.receivePipe = socket;
    }

    @Override
    public void run(Object[] args, ZContext ctx, Socket pipe) {
      try {
        socket = ctx.createSocket(type);
        socket.setDelayAttachOnConnect(true);
        socket.setLinger(60*1000);
        socket.setTCPKeepAlive(1);
        for (String endpoint : addresses.split(",")) {
          if (bind) {
            System.out.println("bind to " + addresses);
            socket.bind(endpoint);
          } else {
            System.out.println("connect to " + addresses);
            socket.connect(endpoint);
          }
        }
        String identity = String.format("%04X-%04X", rand.nextInt(0x10000), rand.nextInt(0x10000));
        socket.setIdentity(identity.getBytes());
        System.out.println("Socket has identity " + identity);

        PollItem[] items =
            {new PollItem(pipe, ZMQ.Poller.POLLIN), new PollItem(socket, ZMQ.Poller.POLLIN)};
        while (!Thread.currentThread().isInterrupted()) {
          int rc = ZMQ.poll(items, 2000);
          if (rc == -1) {
            System.out.println("Broken pipe for " + this.toString());
            break;
          }
          if (items[0].isReadable()) { // send
            ZMsg msg = ZMsg.recvMsg(pipe, ZMQ.DONTWAIT);
            if (msg == null) {
              System.out.println("Exception: readabe but message is null.");
            }
            if (type == ZMQ.ROUTER || type == ZMQ.PUB) {
              ZFrame address = msg.pop();
              address.send(socket, ZFrame.REUSE + ZFrame.MORE);
              // address.destroy();
            }
            ZFrame content = msg.pop();
            while (content != null && content.hasData()) {
              boolean b = content.send(socket, ZFrame.REUSE);
              if (!b) {
                System.out.println("sendable2 send failed.");
              }
              content = msg.pop();
            }
          }

          if (items[1].isReadable()) { // receive
            ZMsg msg = ZMsg.recvMsg(socket, ZMQ.DONTWAIT);
            if (msg == null) {
              System.out.println("Exception:receivable but message is null.");
            } else {
              msg.send(receivePipe);
            }
          }
        }
      } catch (Exception e) {
        e.printStackTrace();
      }
    }
  }

  private class Receiver implements IAttachedRunnable {
    private final Queue<TaskMessage> queue;
    private boolean oneWay;

    public Receiver(Queue<TaskMessage> queue, boolean oneWay) {
      super();
      this.queue = queue;
      this.oneWay = oneWay;
    }

    @Override
    public void run(Object[] args, ZContext ctx, Socket pipe) {
      try {
        if (oneWay) {
          socket = ctx.createSocket(type);
          for (String endpoint : addresses.split(",")) {
            if (bind) {
              System.out.println(
                  String.format("[%s] bind to %s", Thread.currentThread().getName(), addresses));
              socket.bind(endpoint);
            } else {
              System.out.println(
                  String.format("[%s] connect to %s", Thread.currentThread().getName(), addresses));
              socket.connect(endpoint);
            }
          }
        }

        PollItem[] items = new PollItem[oneWay ? 2 : 1];
        if (oneWay) {
          items[0] = new PollItem(pipe, ZMQ.Poller.POLLIN);
          items[1] = new PollItem(socket, ZMQ.Poller.POLLIN);
        } else {
          items[0] = new PollItem(pipe, ZMQ.Poller.POLLIN);
        }

        while (!Thread.currentThread().isInterrupted()) {
          int rc = ZMQ.poll(items, 2000);
          if (rc == -1) {
            System.out.println("Broken pipe for " + this.toString());
            break;
          }

          if (items[0].isReadable()) { // receive from DEALER/ROUTER routing
            ZMsg msg = ZMsg.recvMsg(pipe, ZMQ.DONTWAIT);
            if (msg == null) {
              System.out.println("Exception: received from DEALER/ROUTER msg receivable but null");
            }

            byte[] param = null;
            if (type == ZMQ.ROUTER) {
              ZFrame address = msg.pop();
              param = address.getData();
            } else {
              param = new byte[0];
            }
            ZFrame content = msg.pop();
            while (content != null && content.hasData()) {
              byte[] data = content.getData();
              TaskMessage tm = new TaskMessage(ByteBuffer.wrap(data), param);
              queue.add(tm);
              content = msg.pop();
            }
          }
          if (oneWay) {

            if (items[1].isReadable()) { // receive from socket
              ZMsg msg = ZMsg.recvMsg(socket, ZMQ.DONTWAIT);
              if (msg == null) {
                System.out.println("Exception: received from socket msg receivable but null");
              }
              String param = null;
              if (type == ZMQ.ROUTER) {
                param = new String(msg.pop().getData()).trim();
              } else if (type == ZMQ.SUB) {
                msg.pop(); // ignore the subject
              }

              ZFrame dataFrame = msg.pop();
              if (dataFrame != null && dataFrame.hasData()) {
                byte[] data = dataFrame.getData();
                TaskMessage tm = new TaskMessage(ByteBuffer.wrap(data));
                queue.add(tm);
              }
            }
          }
        }
      } catch (Exception e) {
        e.printStackTrace();
      }
    }
  }

  private void createSocket() {
    if (addresses != null) {
      if (type == ZMQ.PUB || type == ZMQ.PUSH) {
        sendPipe = ZThread.fork(context, new Sender());
      }
      if (type == ZMQ.PULL || type == ZMQ.SUB) {
        receivePipe = ZThread.fork(context, new Receiver(incoming, true));
      }

      if (type == ZMQ.DEALER || type == ZMQ.ROUTER) {
        Receiver receiver = new Receiver(incoming, false);
        receivePipe = ZThread.fork(context, receiver);
        Sender sender = new Sender(receivePipe);
        sendPipe = ZThread.fork(context, sender);
      }
    }
  }

  public void close() {
    if (this.socket != null) {
      this.socket.close();
    }
  }

  public boolean send(ByteBuffer message, byte[] session) {
    TaskMessage tm = new TaskMessage();
    tm.setBuffer(message);
    tm.setSession(session);
    outgoing.add(tm);
    return true;
  }

  public boolean send(ByteBuffer message) {
    TaskMessage tm = new TaskMessage();
    tm.setBuffer(message);
    outgoing.add(tm);
    return true;
  }

  public void registerListener(MessageListener listener) {
    this.listener = listener;
  }

  public String toString() {
    return String.format("%s-%s", addresses, bind);
  }
}
```

TaskMessage.java

```java
package com.jeromq.test;

import java.nio.ByteBuffer;

public class TaskMessage {

  private ByteBuffer buffer ;
  private String subject;
  private byte[] session;
  
  public TaskMessage() {
    super();
  }
  
  public TaskMessage(boolean allocate) {
    super();
    if(allocate){
//      buffer = ByteBuffer.allocateDirect(1024);
    }
  }

  public TaskMessage(ByteBuffer buffer) {
    this.buffer = buffer;
  }

  public TaskMessage(String subject, ByteBuffer buffer) {
    this.buffer = buffer;
    this.subject = subject;
  }

  public TaskMessage(ByteBuffer buffer,byte[] session) {
    this.buffer = buffer;
    this.session = session;
  }
  
  public void setBuffer(ByteBuffer buffer) {
    this.buffer = buffer;
  }
  
  public void setSubject(String subject) {
    this.subject = subject;
  }

  public void setSession(byte[] session) {
    this.session = session;
  }

  public ByteBuffer getBuffer() {
    return this.buffer;
  }

  public String getSubject() {
    return subject;
  }
  
  public byte[] getSession() {
    return session;
  }
}
```

MessageListener.java

```java
package com.jeromq.test;

public interface MessageListener {
  public void onMessage(TaskMessage message);
}
```

AsyncServer.java

```java
package com.jeromq.test;

import org.zeromq.ZContext;
import org.zeromq.ZMQ;

public class AsyncServer {
  public static void main(String[] args) {
    ZContext context = new ZContext();
    ZeroMQTransport transport = new ZeroMQTransport(context,"tcp://*:5678",ZMQ.ROUTER,true);
    transport.registerListener(new MessageListener() {
      
      @Override
      public void onMessage(TaskMessage message) {
        transport.send(message.getBuffer(), message.getSession());
      }
    });
    transport.start();
  }
}
```

AsyncClient.java

```java
package com.jeromq.test;

import java.nio.ByteBuffer;
import org.zeromq.ZContext;
import org.zeromq.ZMQ;

public class AsyncClient {
  public static void main(String[] args) {
    int count = 10000000;//Integer.parseInt(args[0]);
    ZContext context = new ZContext();
    ZeroMQTransport transport = new ZeroMQTransport(context,"tcp://127.0.0.1:5678",ZMQ.DEALER,false);
    transport.registerListener(new MessageListener() {
      long i=0;
      @Override
      public void onMessage(TaskMessage message) {
        long data = message.getBuffer().getLong();
        if(i!=data){
          System.out.println(i+"  vs "+data);
          System.exit(-1);
        }else{
          i++;
        }
        if(i==count-1){
          System.out.println("Done receive.");
        }
      }
    });
    transport.start();
    
    for(int i=0;i<count;i++){
      ByteBuffer buffer = ByteBuffer.allocateDirect(8);
      buffer.putLong(i).flip();
      transport.send(buffer);
    }
    System.out.println("Done send.");
  }
}
```

Thanks for your time again.

btw, i tested jeromq 0.3.4/0.3.6, the same result.

Gazit

_EDIT: code formatting - @daveyarwood_

**Comment by daveyarwood** [comment] 2016-11-11 14:45
There is too much code here for us to reasonably find the cause of the behavior you're seeing. It could be so many things! It would be helpful if there were a simpler example demonstrating the problem you're seeing.

I did spend a few minutes looking at your code, and I noticed a few things that look suspect:

- You have a lot of code that seems to be replicating behavior that ZeroMQ already provides out-of-the-box. For example, you're setting up LinkedBlockingQueues for outgoing and incoming messages. There is no need to do that; ZMQ sockets already have message queues built-in. For the most part, your code should just be binding/connecting sockets and receiving/sending messages to/from the sockets.

- If I'm reading your code correctly, it seems like you are trying to create sockets dynamically depending on the type of message that is being received. This is not idiomatic for ZMQ. Instead, I would recommend creating 1 socket for each of the types of sockets you need to create (e.g. 1 PULL socket, 1 SUB socket, 1 DEALER socket, etc.), and let each of those sockets have its own queue. Again, this queue is built into the socket, not something you need to implement with e.g. a LinkedBlockingQueue.

I would encourage you to spend some time reading through the [ZGuide](http://zguide.zeromq.org/) to understand more of the philosophies behind designing an application with ZeroMQ.

**Comment by GazitGu** [comment] 2016-11-13 04:44
Hi daveyarwood,

Thanks for your time. 

Let me explain something:
1. As i know that JeroMQ/JZMQ Socket is not thread-safe,  so i use a blocking queue to let the message can be send from any thread (Please let me know if the socket is thread-safe).
2. The ZeroMQTransport is per instance per ZMQ type, but the receiver is useless here for router/dealer type, i will remote it and give a clean  prototype.


Thanks  again.

Gazit

**Comment by GazitGu** [comment] 2016-11-14 05:08
Hi daveyarwood,

I have removed useless code and here is the clean ZeroMQTransport.java

The test scenario is AsyncServer as echo server and AsyncClient send continuous number to see if any message missed. (this can easily test latency if change continuous number to current nano).

package com.jeromq.test;


import java.nio.ByteBuffer;
import java.util.Random;
import java.util.concurrent.BlockingQueue;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.LinkedBlockingQueue;

import org.zeromq.ZContext;
import org.zeromq.ZFrame;
import org.zeromq.ZMQ;
import org.zeromq.ZMQ.PollItem;
import org.zeromq.ZMQ.Socket;
import org.zeromq.ZMsg;
import org.zeromq.ZThread;
import org.zeromq.ZThread.IAttachedRunnable;

public class ZeroMQTransport {
  private final ZContext context;
  private Socket socket;
  private Socket sendPipe;
  private final String addresses;
  private final int type;
  private final boolean bind;


  private MessageListener listener;



  private BlockingQueue<TaskMessage> outgoing = new LinkedBlockingQueue<TaskMessage>();

  private final ExecutorService outgoingExecutorService = Executors.newSingleThreadExecutor();

  public ZeroMQTransport(final ZContext context, final String addresses, int type, boolean bind) {
    this.context = context;
    this.type = type;
    this.addresses = addresses;
    this.bind = bind;
  }

  public void start() {
    outgoingExecutorService.execute(new Runnable() {
      public void run() {
        try {
          while (true) {
            TaskMessage tm = outgoing.take();
            onOutgoingMessage(tm);
          }
        } catch (Exception e) {
          e.printStackTrace();
        }
      }
    });
    createSocket();
  }

  private void onOutgoingMessage(TaskMessage event) {
    try {
      if (type == ZMQ.ROUTER) {
        byte[] address = event.getSession();
        if (address != null) {
          sendPipe.send(address, ZFrame.REUSE + ZFrame.MORE);
        } else {
          System.out.println("Router send message but without session combined.");
          return;
        }
      }

      ByteBuffer buffer = event.getBuffer();
      byte[] b = new byte[buffer.remaining()];
      buffer.mark();
      buffer.get(b);
      buffer.reset();


      boolean bo = sendPipe.send(b, 0);
      if (!bo) {
        System.out.println("Received send failed.");
      }
    } catch (Exception e) {
      e.printStackTrace();
    }
  }

  private class Sender implements IAttachedRunnable {

    private Random rand = new Random(System.nanoTime());

    @Override
    public void run(Object[] args, ZContext ctx, Socket pipe) {
      try {
        socket = ctx.createSocket(type);
        socket.setDelayAttachOnConnect(true);
        socket.setLinger(60 * 1000);
        socket.setTCPKeepAlive(1);
        if (bind) {
          System.out.println("bind to " + addresses);
          socket.bind(addresses);
        } else {
          System.out.println("connect to " + addresses);
          socket.connect(addresses);
        }
        String identity = String.format("%04X-%04X", rand.nextInt(0x10000), rand.nextInt(0x10000));
        socket.setIdentity(identity.getBytes());
        System.out.println("Socket has identity " + identity);

        PollItem[] items =
            {new PollItem(pipe, ZMQ.Poller.POLLIN), new PollItem(socket, ZMQ.Poller.POLLIN)};
        while (!Thread.currentThread().isInterrupted()) {
          int rc = ZMQ.poll(items, 2000);
          if (rc == -1) {
            System.out.println("Broken pipe for " + this.toString());
            break;
          }
          if (items[0].isReadable()) { // send
            ZMsg msg = ZMsg.recvMsg(pipe, ZMQ.DONTWAIT);
            if (msg == null) {
              System.out.println("Exception: readabe but message is null.");
            }
            if (type == ZMQ.ROUTER) {
              ZFrame address = msg.pop();
              address.send(socket, ZFrame.REUSE + ZFrame.MORE);
            }
            ZFrame content = msg.pop();
            while (content != null && content.hasData()) {
              boolean b = content.send(socket, ZFrame.REUSE);
              if (!b) {
                System.out.println("sendable2 send failed.");
              }
              content = msg.pop();
            }

          }

          if (items[1].isReadable()) { // receive
            ZMsg msg = ZMsg.recvMsg(socket, ZMQ.DONTWAIT);
            if (msg == null) {
              System.out.println("Exception:receivable but message is null.");
            } else {
              byte[] param = null;
              if (type == ZMQ.ROUTER) {
                ZFrame address = msg.pop();
                param = address.getData();
              } else {
                param = new byte[0];
              }
              ZFrame content = msg.pop();
              while (content != null && content.hasData()) {
                byte[] data = content.getData();
                TaskMessage tm = new TaskMessage(ByteBuffer.wrap(data), param);
                listener.onMessage(tm);
                content = msg.pop();
              }
            }
          }
        }
      } catch (Exception e) {
        e.printStackTrace();
      }

    }

  }


  private void createSocket() {
    if (addresses != null) {
      Sender sender = new Sender();
      sendPipe = ZThread.fork(context, sender);
    }
  }


  public void close() {
    if (this.socket != null) {
      this.socket.close();
    }
  }



  public boolean send(ByteBuffer message, byte[] session) {
    TaskMessage tm = new TaskMessage();
    tm.setBuffer(message);
    tm.setSession(session);
    outgoing.add(tm);
    return true;
  }

  public boolean send(ByteBuffer message) {
    TaskMessage tm = new TaskMessage();
    tm.setBuffer(message);
    outgoing.add(tm);
    return true;
  }



  public void registerListener(MessageListener listener) {
    this.listener = listener;

  }


  public String toString() {
    return String.format("%s-%s", addresses, bind);
  }
}

Please let me know if any findings.

Thanks again for your time.

Gazit

**Comment by GazitGu** [comment] 2016-11-19 03:45
Hi all,

I am not sure why but when i setHWM(0), the message lost issue disappear.

**Comment by daveyarwood** [comment] 2018-10-28 01:36
I'm going to take the liberty of closing this issue, as it's been almost 2 years since the last activity and it wasn't really clear what the issue was to begin with.

**Closed by daveyarwood** 2018-10-28 01:36 UTC
