### ISSUE TITLE
Intermittent NullPointerException and hang when terminating context

### ISSUE THREAD

**Issue by hiteshjasani** [zeromq/jeromq#302] opened 2015-11-19 19:00 UTC
Hey, when running jeromq 0.3.5 I'm seeing an intermittent hang when terminating the context.  Sometimes when it hangs, it also prints out an exception.

```
Exception in thread "reaper-1" java.lang.NullPointerException
        at zmq.Pipe.processPipeTermAck(Pipe.java:396)
        at zmq.ZObject.processCommand(ZObject.java:97)
        at zmq.SocketBase.processCommands(SocketBase.java:863)
        at zmq.SocketBase.inEvent(SocketBase.java:968)
        at zmq.Poller.run(Poller.java:247)
        at java.lang.Thread.run(Thread.java:745)
```

My code is actually in clojure, but it is creating a `ZMQ$Context` object and then calling the `.term()` method on it when the problem happens.  By the time I'm trying to terminate the context, the sockets are already closed.  I've also tried unregistering the socket from the poller before closing it, but it didn't make any difference.

Since this occurs on shutting down my app it's not critical, but I kinda want to make sure no resources are leaking.

**Comment by miniway** [comment] 2015-11-19 19:29
Could you upload your code in the gist? Someone who can understand Clojure would help. Basically `ZMQ$Context` is not always thread safe. If you call the `.term()` in the other thread where the context not is created, it can cause some issues.

**Comment by hiteshjasani** [comment] 2015-11-19 19:55
The code isn't easy to extract, but I can give a high level view of what I'm doing.  It's basically built off of the [multi-threaded server example](http://zguide.zeromq.org/clj:mtserver).  I create the context in the main thread, use it in the worker threads, but only terminate it in the main thread when all the worker threads are done.

https://gist.github.com/hiteshjasani/0e1b2869d62f0ee7856e

**Comment by hiteshjasani** [comment] 2015-11-20 13:15
Update: I've added a sleep statement before the context termination that seems to have addressed the intermittent hang -- see the updated gist.  I believe it has something to do with the linger value (100ms) on the sockets created in the thread and the termination of the context.  If I give enough time between  (socket close time + socket linger offset) and (term context time) then everything seems fine.

**Comment by miniway** [comment] 2015-12-07 03:14
If you want to use the Context in another threads which is created on the main thread, it should be shadowed at the worker thread. Could you please look into https://github.com/miniway/zper/blob/master/src/main/java/org/zper/ZPer.java

**Comment by ThunderSOS** [comment] 2016-01-13 16:29
I'm seeing this intermittently too. In my case the Context is created and destroyed by Spring so it is always done in the same thread. I'm pretty sure this only started happening in the 0.3.5 release.

**Comment by metabrain** [comment] 2016-01-13 16:48
I've been seeing beginning at around 6 months ago with our software once we started using JeroMQ. I've also resorted to the timeout hot-fix as well, around 1000ms for us seems to do it in 100% of the cases. But it is something we'd rather get rid off.

For reference, we use 0.3.5 as well:
```xml
		<dependency>
			<groupId>org.zeromq</groupId>
			<artifactId>jeromq</artifactId>
			<version>0.3.5</version>
		</dependency>
```

**Comment by ThunderSOS** [comment] 2016-01-13 17:38
Doing a sleep() before closing the Context, the sockets have already been requested to shut down, seems to work for me too so this may be a clue to a fix. 
The shut down sequence looks like this: 

2016-01-13 17:28:35,926 [INFO] MessageSubscriberWorker - Shutting down MessageWorker
2016-01-13 17:28:35,926 [DEBUG] MessageSubscriberWorker - Thread interrupted
2016-01-13 17:28:35,927 [INFO] MessageSubscriberWorker - MessageWorker thread exited
2016-01-13 17:28:35,927 [INFO] .MessageSubscriberService - Closing MessageSubscriber 
2016-01-13 17:28:35,927 [DEBUG] zmq.ZmqMessageSubscriber - Disconnecting ZMQ socket
2016-01-13 17:28:35,928 [INFO] MessageSubscriberService - Shutting down Subscriber thread
2016-01-13 17:28:35,928 [INFO] zmq.ZmqContextHolder - Wait 2 seconds then close context. Closing ZMQ context

Typically the server got stuck at the last line until a wait was added. Bit of a nasty fix (how long is long enough?) but it seems to work.

**Comment by miniway** [comment] 2016-01-13 17:52
I might need to look into what have been changed in the realease 0.3.5 

If you are able to produce a reproducible code, it would be very useful.

**Comment by lightningrob** [comment] 2017-02-11 01:31
I am hitting the same issue when trying to shut down zmq, where ctx.term() hangs.  Adding a 2 second sleep didn't help, and for me this is 100% reproducible, not intermitent.  I'm not directly spawning any other threads besides the main one.

An update from the maintainers would be appreciated.

**Comment by daveyarwood** [comment] 2017-02-11 16:04
The stacktrace suggests that it's possible to run into a NPE [here](https://github.com/zeromq/jeromq/blob/v0.3.5/src/main/java/zmq/Pipe.java#L396):

```java
while (inpipe.read() != null) {
    // do nothing
}

inpipe = null;
```

My guess is that multiple threads are trying to close the same pipe at the same time, so `inpipe` is being set to `null` and then the next thread tries to call `.read()` on it.

We can fix this (at least to some degree) by bailing out early if `inpipe` is already `null`. I'll make a PR with that change.

**Closed** 2017-02-11 17:11 UTC
