### ISSUE TITLE
Reaper/iothread leak !!

### ISSUE THREAD

**Issue by prashant68** [zeromq/jeromq#282] opened 2015-08-20 15:09 UTC
HI Guys,

I am seeing issue with reaper and io threads are leaking.    Here are stack i capture from yourkit.. I am creating Poller for each client's session and tearing them down client disconnect.  All of there threads and sockets i create are getting cleaned up; however these hang around and in running state...

```
reaper-1 [RUNNABLE, IN_NATIVE] [DAEMON]
sun.nio.ch.SelectorImpl.select(long) SelectorImpl.java:97
zmq.Poller.run() Poller.java:216
java.lang.Thread.run() Thread.java:745

iothread-2 [RUNNABLE, IN_NATIVE] [DAEMON]
sun.nio.ch.SelectorImpl.select(long) SelectorImpl.java:97
zmq.Poller.run() Poller.java:216
java.lang.Thread.run() Thread.java:745
```

Sample code

```java
  public void run() {
    worker = workerCtx.createSocket(ZMQ.DEALER);
    worker.setLinger(0);
    worker.connect(ZMQAsyncRequestReply.INPROC_URL_PREFIX + sessionId);
    poller.register(worker, ZMQ.Poller.POLLIN);
    LOG.info("Starting reader thread [{}]", getId());
    try {
      while (!done && !Thread.currentThread().isInterrupted()) {
        poller.poll(pollTimeout);
        if (!poller.pollin(0)) {
          //not signalled msg, step to next wait loop
          continue;
        }
        ZMsg msg = ZMsg.recvMsg(worker);
        ZFrame senderAddr = msg.getFirst();
        ZFrame content = msg.getLast();
        byte[] decomp = ZMQUtility.decompress(content.getData());
        String msgStr = new String(decomp, ZMQ.CHARSET);
        EnvMsg envMsg = gson.fromJson(msgStr, EnvMsg.class);

    // Do some processing...

    content.destroy();
    senderAddr.destroy();
    msg.destroy();
  }
} catch (Throwable e) {
}
LOG.info("Stopping reader thread [{}]", getId());
poller.unregister(worker);
workerCtx.destroy();
LOG.info("Stopped reader thread [{}]", getId());
  }
```

Execution from code ----
```
err.out:[ZMQAsyncReplierWorker--5349037352676564992-0] INFO ZMQAsyncReplierWorker - Starting reader thread [tcp://192.168.5.25:51021-(-5349037352676564992)-(0)]
err.out:[ZMQAsyncReplierWorker--5349037352676564992-0] INFO ZMQAsyncReplierWorker - Stopping reader thread [tcp://192.168.5.25:51021-(-5349037352676564992)-(0)]
err.out:[ZMQAsyncReplierWorker--5349037352676564992-0] INFO ZMQAsyncReplierWorker - Stopped reader thread [tcp://192.168.5.25:51021-(-5349037352676564992)-(0)]
```

Thank you

_EDIT: code formatting - @daveyarwood_

**Comment by miniway** [comment] 2015-11-09 00:49
I'm not sure as I can reproduce in my sandbox, but if `workerCtx` is created from another thread (ex main thread), there would be an issue at cleanup. Please refer https://github.com/zeromq/jeromq/wiki/Sharing-ZContext-between-thread

**Comment by cystek** [comment] 2016-01-19 20:52
I've been experiencing this same issue. I've tried a few different configurations with the same result of reaper and iothread threads steadily rising as the program runs (detected via jstack). Originally, I used ZMQ.Context (which is supposed to be thread safe pre the documentation), followed by ZContext alone (which I would expect to leak threads but wanted to try), then ZContext with the shadow context method as described in the link above by having a static base ZContext (never used to create sockets) and a ThreadLocal<ZContext> which uses ZContext.shadow(baseContext) when creating new instances. All methods leaked iothread and reaper threads. All ZMQ logic is wrapped in a cleass and I use 10 worker threads and ZMQ.REQ in all methods attempted with the socket instances being allocated and closed/destroyed after each use of the enclosing method, so the sockets should not be touching any thread other than the one calling the method. For completeness, the ZMQ.REP end of logic operates only in main (of a different application and also with 10 worker threads) and does not leak any threads.  This appears to be a legitimate issue since the first and third methods I tried should have worked based on my understanding of the library. Thanks.

**Comment by daveyarwood** [comment] 2017-10-05 03:10
This issue has to do with polling resources not being cleaned up when a context is terminated. This is something I fixed myself, so I'm familiar with the code. It used to be the case that pollers were not managed by the context, but via an error-prone ThreadLocal variable that was, of course, not thread-safe. The fix was to make it so that you have to create a poller via a context, and then the context manages the lifecycle of the poller, cleaning it up when the context is destroyed.

It's been over 2 years since this issue was created and I'm pretty sure it's been fixed for a while, and at any rate, the code base is totally different now. So, I'm closing this issue. If anyone is experiencing a related issue with the latest version of JeroMQ, please create a new issue.

**Closed by daveyarwood** 2017-10-05 03:10 UTC
