### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by Biribu** [zeromq/jeromq#183] opened 2014-08-20 08:16 UTC
I am having this issue after some hours of good working:

zmq.ZError$IOException: java.io.IOException: Too many open files
    at zmq.Signaler.make_fdpair(Signaler.java:87)
    at zmq.Signaler.<init>(Signaler.java:48)
    at zmq.Mailbox.<init>(Mailbox.java:55)
    at zmq.Ctx.<init>(Ctx.java:127)
    at zmq.ZMQ.zmq_ctx_new(ZMQ.java:225)
    at zmq.ZMQ.zmq_init(ZMQ.java:258)
    at org.jeromq.ZMQ$Context.<init>(ZMQ.java:173)
    at org.jeromq.ZMQ.context(ZMQ.java:155)
    at ... (my files )
    at java.lang.Thread.run(Thread.java:744)
Caused by: java.io.IOException: Too many open files
    at sun.nio.ch.IOUtil.makePipe(Native Method)
    at sun.nio.ch.PipeImpl.<init>(PipeImpl.java:42)
    at sun.nio.ch.SelectorProviderImpl.openPipe(SelectorProviderImpl.java:50)
    at java.nio.channels.Pipe.open(Pipe.java:150)
    at zmq.Signaler.make_fdpair(Signaler.java:85)
    ... 11 more]]

I am running this java server in Glassfish. I don't know if it is my fault or I should ask to system admin to check glassfish instance.

My ZMQ code: 

```
            ZMQ.Context context = ZMQ.context(1);
    ZMQ.Socket sender = context.socket(ZMQ.PUSH);
    sender.connect("tcp://127.0.0.1:8083");
    sender.send(device, ZMQ.SNDMORE);
    sender.send("obs", ZMQ.SNDMORE);
    sender.send("["+message+"]", 0);
    sender.close();
        context.term(); 
```

I have this code inside a class created in a background thread. Each time I get a post to the server, I call new thread and create an instance of this class.

**Comment by trevorbernard** [comment] 2015-07-15 17:58
@Biribu: I believe this may have been resolved

**Comment by spyhunter99** [comment] 2015-07-16 11:02
Just an FYI, I'm running into the same issue on android based devices.

**Comment by trevorbernard** [comment] 2015-07-16 11:03
@spyhunter99: Are you using v0.3.5?

**Comment by spyhunter99** [comment] 2015-07-16 11:09
I think we're still on 0.3.3. Looks like upgrading will be in the near future. This was on a 6 activity application and the node was attached to the activity. Rapidly switching between activities would stand up and tear down the stack thus making this problem painfully obvious.

**Comment by trevorbernard** [comment] 2015-07-16 11:12
There was a patch submitted in 0.3.5-SNAPSHOT that specifically addressed leaking socket resources

**Comment by daveyarwood** [comment] 2016-09-04 23:08
For what it's worth, I'm seeing the `java.io.IOException: Too many open files` error with both jeromq 0.33 and 0.3.5.

What I'm doing is a little complicated, but [this is the commit](https://github.com/alda-lang/alda/commit/e005d8c8c474ead484d147b96c391ef2f558483f) where I updated to jeromq 0.3.5 and also made a change where we make sure to close all input, output, and error streams when spinning off separate processes that communicate with each other via ZMQ sockets. The setup is a client <-> server <-> workers "paranoid pirate pattern" with two ROUTER sockets. Lots of heartbeats going around between the server and workers, lots of messages being sent.

I'm running into the "Too many open files" error sometimes after starting 6-10 worker processes. Another Alda user with a slower computer (and possibly a lower `ulimit -n`... I have mine at 10480) reported seeing the error with 4 worker processes.

**Comment by daveyarwood** [comment] 2016-09-04 23:25
@trevorbernard I just stumbled upon this answer you gave to a related question on StackOverflow: http://stackoverflow.com/a/25478590/2338327

Here you're recommending not destroying and re-creating contexts and sockets, which is at odds with [what I'm doing in the Alda client](https://github.com/alda-lang/alda/blob/master/client/src/alda/AldaRequest.java#L62-L67). My code here is loosely based on [this example Java code](http://zguide.zeromq.org/java:lpclient) found in the [Lazy Pirate Pattern](http://zguide.zeromq.org/page:all#toc89) section of the ZeroMQ Guide, so I figured it would be idiomatic, but perhaps not?

**Comment by daveyarwood** [comment] 2016-12-07 04:18
I am inclined to believe that the following code from the ZGuide Lazy Pirate Pattern example is bad and should be removed:

(Context: this code is run before every retry if there is no response from the server)

```java
//  Old socket is confused; close it and open a new one
ctx.destroySocket(client);
System.out.println("I: reconnecting to server\n");
client = ctx.createSocket(ZMQ.REQ);
client.connect(SERVER_ENDPOINT);
//  Send request again, on new socket
client.send(request);
```

It seems like repeatedly destroying, re-creating and re-connecting the client socket is not recommended, and it's probably better to keep re-sending the request from the same client socket.

**Comment by czardonic** [comment] 2017-03-15 15:02
I am also having issues with 'too many files open', particularly around connections to unreachable/unresponsive servers

I have tried 3 options - 
1. Lazy pirate pattern - I would tend to agree with @daveyarwood in that ZGuide code doesn't seem to behave well here. ctx.destroySocket code doesn't seem to do anything but clear it out of the ctx's structures, all the sockets resources are still left around.

Modifying the reqrep unit test I can get it to fail with too many files open exception:
```java
    Ctx ctx = ZMQ.init(1);
    assertThat(ctx, notNullValue());
    for (int i = 0; i < 40000; ++i) {
        int port = Utils.findOpenPort();

        boolean rc;

        SocketBase sc = ZMQ.socket(ctx, ZMQ.ZMQ_REQ);
        assertThat(sc, notNullValue());
        rc = ZMQ.connect(sc, "tcp://127.0.0.1:" + port);
        assertThat(rc, is(true));
        
        byte[] content = "12345678ABCDEFGH12345678abcdefgh".getBytes(ZMQ.CHARSET);
        int rci = ZMQ.send(sc, content, 32, 0);
        assert (rci == 32);

        ctx.destroySocket(sc);
    }
    ZMQ.term(ctx);
```
2. Rebuild the context
```java
    for (int i = 0; i < 40000; ++i) {
        Ctx ctx = ZMQ.init(1);
        assertThat(ctx, notNullValue());
        int port = Utils.findOpenPort();

        boolean rc;
        SocketBase sc = ZMQ.socket(ctx, ZMQ.ZMQ_REQ);
        assertThat(sc, notNullValue());
        rc = ZMQ.connect(sc, "tcp://127.0.0.1:" + port);
        assertThat(rc, is(true));
        
        byte[] content = "12345678ABCDEFGH12345678abcdefgh".getBytes(ZMQ.CHARSET);
        int rci = ZMQ.send(sc, content, 32, 0);
        assert (rci == 32);

        sc.close();
        ZMQ.term(ctx);
    }
```
This hangs on ZMQ.term as the socket never gets destroyed (it never gets the last TERM_ACK it needs to processDestroy). If I never send a message or if i do get a message then it cleans up fine. There seems to be a long sequence of events that need to happen for a socket to be destroyed and I only traced it back as far as not getting a PIPE_TERM on the ReqSession

3. close (rather than destroy the socket) -- Suffers the same problem as #2 as the sockets will never clean up, you just wont hang on the ctx.term

Is there a proper way to handle this situation where we never get a response from the server?

The unit tests were run on master, but the my code that's failing is using 0.3.6

**Comment by daveyarwood** [comment] 2017-03-17 12:22
> what is your open files count from 'ulimit -n'. If it is 1024 it would not be enough for hundreds of ZMQ sockets.

I think this is very important. If this number is too low, I think the test cases we're talking about are always going to fail.

**Comment by czardonic** [comment] 2017-03-17 12:43
Unless there's an API call I'm missing, the intention of my tests are to clean up the sockets immediately so there should only be ever 1 in existence at a time

**Comment by daveyarwood** [comment] 2017-03-17 13:26
If I'm not mistaken, the "files" (i.e. socket handles on your system) remain open for some undetermined period of time, even after you've destroyed the ZMQ socket object and it's been garbage collected. This has to do with the OS, not ZeroMQ or even Java, and it's directly connected to `ulimit -n` and the "Too many open files" exception.

**Comment by czardonic** [comment] 2017-03-17 13:54
In my real-world application I'm seeing these persist beyond 15 minutes (and this is on Windows which in my experience tends to have faster cleanup in these sort of situations).

In my reading of the code and debugging, it's because the socket processDestroy doesn't get invoked because the necessary commands don't seem to get sent.

I will adjust my tests to account for the possibility of OS delay on the cleanup

**Comment by daveyarwood** [comment] 2017-03-17 13:57
> In my reading of the code and debugging, it's because the socket processDestroy doesn't get invoked because the necessary commands don't seem to get sent.

Would you mind expanding on this? Where in the code is this?

**Comment by czardonic** [comment] 2017-03-17 14:07
I haven't yet fully traced it back (I might have time to do this later) but, from what I read the fd's are mostly from the epolls setup by the mailbox which gets destroyed by socket's processDestory.

socket.processDestroy comes from:

processDestory <- (command) Req.TERM_ACK <- ReqSession.TERM <- ReqSession.pipeTerminated

Which, in the working situation of ( connect + close -- without a send ) gets triggered by TCPConnector processing its TERM command.

I'm not familiar enough with jmq to know what all the objects are that need to be collected/TERMed to properly trigger the socket to cleanup, other than it seems sockets are not 'owned' by anyone and rely on the pipe being TERMed

**Comment by daveyarwood** [comment] 2017-04-27 10:18
Every socket belongs to a ZeroMQ "context" -- the base class for this is called Ctx, and there are higher level implementations wrapping it: ZMQ$Context and (higher-level) ZContext.

When a context is terminated, it is responsible for destroying and cleaning up its resources, which include sockets, pollers and selectors.

**Comment by daveyarwood** [comment] 2017-04-27 11:11
I think I've finally figured out how to reconcile the seemingly conflicting information that I've read.

To recap, I've read both of these ideas in various places:

1. The Lazy Pirate client pattern recommends destroying and re-creating a client socket when a request times out. You do this in a loop until you get a response.

2. It is not recommended that you create and destroy sockets in a tight loop.

Idea 2 is very important, especially if your `ulimit -n` is low, like it is by default in many OS's. When writing an end-user application, we cannot expect all users to know about `ulimit -n` and to have increased the limit on their system. So, it is up to us to code responsibly to ensure that we don't blow past the limit and cause the application to crash.

Idea 1 is also a good pattern because due to a variety of factors including network connectivity issues, retrying is crucial for client-side reliability.

For Idea 1 to work without causing problems related to Idea 2, the key thing is timing. You can't write code that runs in a tight loop and retries constantly, especially if you are destroying and creating a socket every time you retry. You need to do something more responsible, like retry every 2500 ms up to a limit of 3 times total. See [lpclient.java](https://github.com/zeromq/jeromq/blob/master/src/test/java/guide/lpclient.java) for an implementation of this.

**Closed by daveyarwood** 2017-04-27 11:11 UTC

**Comment by aristodemos** [comment] 2017-08-02 08:22
To all, I had a similar issue using the MDP example (the synchronous one).
This is the exception I had (similar to all 3 components).
`Exception in thread "main" zmq.ZError$IOException: java.io.IOException: Too many open files in system
	at zmq.Ctx.createSelector(Ctx.java:480)
	at org.zeromq.ZMQ$Context.selector(ZMQ.java:366)
	at org.zeromq.ZMQ$Poller.<init>(ZMQ.java:2646)
	at org.zeromq.ZContext.createPoller(ZContext.java:133)
	at main.mdbroker.mediate(mdbroker.java:112)
	at main.mdbroker.main(mdbroker.java:87)
	at main.mdpApp.main(mdpApp.java:9)
Caused by: java.io.IOException: Too many open files in system
	at sun.nio.ch.IOUtil.makePipe(Native Method)
	at sun.nio.ch.KQueueSelectorImpl.<init>(KQueueSelectorImpl.java:84)
	at sun.nio.ch.KQueueSelectorProvider.openSelector(KQueueSelectorProvider.java:42)
	at java.nio.channels.Selector.open(Selector.java:227)
	at zmq.Ctx.createSelector(Ctx.java:474)
	... 6 more`

The issue was in all three cases due to the calling of org.zeromq.ZContext.createPoller method in the while loop of each component.

I created a private instance of a Poller obj for each class (mdboker, mdclapi, mdwrkapi) and removed the following code from the while loops. 
`ZMQ.Poller items = ctx.createPoller(1);
items.register(client, ZMQ.Poller.POLLIN);`

Seems good now. 
Any comments welcomed.

**Comment by daveyarwood** [comment] 2017-08-02 13:21
@aristodemos: a PR to fix those examples would be much appreciated!
