### ISSUE TITLE
Implementation BUG: PUB-SUB not working when SUB binds and PUB connects

### ISSUE THREAD

**Issue by vedran6** [zeromq/jeromq#342] opened 2016-04-29 09:15 UTC
When using the PUB-SUB paradigm, I can only get things to work when the SUB socket connects and the PUB socket binds. When I reverse this and make the PUB socket connect and the SUB socket bind, I fail to receive any messages.

Here's the problematic example I'm testing with:

``` java
ZMQ.Context context = ZMQ.context(2);
Socket pub = context.socket(ZMQ.PUB);
Socket sub = context.socket(ZMQ.SUB);
sub.subscribe(new byte[0]);

sub.bind("tcp://localhost:7070");
pub.connect("tcp://localhost:7070");

Thread.sleep(300);

pub.send("test");
Assert.assertEquals("test", sub.recvStr());

pub.close();
sub.close();
context.term();
```

When I change the `connect` and `bind` calls to:

``` java
sub.connect("tcp://localhost:7070");
pub.bind("tcp://localhost:7070");
```

things start working.

According to the ZMQ specification, it shouldn't matter which socket binds and which connects. Am I doing something wrong?

**Comment by daveyarwood** [comment] 2016-11-07 05:42
> According to the ZMQ specification, it shouldn't matter which socket binds and which connects. 

I'm not sure that is entirely accurate. The ZeroMQ Guide says this:

> Although ZeroMQ tries to be neutral about which side binds and which side connects, there are differences. We'll see these in more detail later. The upshot is that you should usually think in terms of "servers" as static parts of your topology that bind to more or less fixed endpoints, and "clients" as dynamic parts that come and go and connect to these endpoints. Then, design your application around this model. The chances that it will "just work" are much better like that.

**Comment by daveyarwood** [comment] 2017-10-05 03:52
Duplicate of #289.

**Closed by daveyarwood** 2017-10-05 03:52 UTC
