### ISSUE TITLE
PUSH Socket `send()` not blocking; PULL Socket not receiving events

### ISSUE THREAD

**Issue by danielunderwood** [zeromq/jeromq#379] opened 2016-10-30 21:16 UTC
I have a simple example with

`Main.java`:

```
import org.zeromq.ZContext;
import org.zeromq.ZMQ;


public class Main {
    public static void main(String[] args){
        // Create and start thread for PULL socket
        PullRunnable pullRunnable = new PullRunnable();
        Thread pullThread = new Thread(pullRunnable);
        pullThread.start();

        // Sleep to make sure PULL socket is bound
        try {
            Thread.sleep(2000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }

        // Create context and socket for PUSH
        ZContext ctx = new ZContext();
        ZMQ.Socket sock = ctx.createSocket(ZMQ.PUSH);
        sock.connect("tcp://localhost:9988");

        // Send messages
        // sock.send() should block if not connected to a PULL socket as per the docs
        for(int i = 0; i < 20; ++i){
            sock.send(Integer.toString(i));
        }

        // Destroy socket and context
        ctx.destroySocket(sock);
        ctx.destroy();

        // Sleep to make sure PULL sockets can receive everything
        try {
            Thread.sleep(2000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }

        // Close runnable and join Pull process
        try {
            pullRunnable.close();
            pullThread.join();
        }
        catch(Exception e){
            e.printStackTrace();
        }

    }
}
```

`PullRunnable.java`:

```
import org.zeromq.ZContext;
import org.zeromq.ZMQ;

import java.io.Closeable;
import java.io.IOException;

public class PullRunnable implements Runnable, Closeable {
    private volatile boolean running = true;
    private ZContext ctx;

    public void run() {
        // Set up context and socket
        ctx = new ZContext();
        ZMQ.Socket pullSock = ctx.createSocket(ZMQ.PULL);

        // Bind socket
        pullSock.bind("tcp://*:9988");

        // Receive in a loop
        String response;
        while(running){
            // Try to receive. Break on ZMQException (socket terminated)
            try {
                response = pullSock.recvStr();
                System.out.println("Event received:\t" + response);
            }
            catch(org.zeromq.ZMQException ex){
                break;
            }
        }

    }

    public void close() throws IOException {
        running = false;

        // Destroy context, which will destroy sockets
        ctx.destroy();
    }
}
```

I am seeing everything start and stop properly, but the PUSH socket's `send()` doesn't block, which the docs indicate that it should do if not connected to a PULL socket. If I remove the socket's `connect()` call, it blocks as expected. Even though it isn't blocking, the PULL socket never seems to receive anything.

I have tried this with maven dependencies of version 0.3.5 and 0.3.6 with both Windows 10 with Oracle's JDK 1.8 and a clean Ubuntu 16.04 VM with openjdk 1.8. Essentially the same code has also been tried on a few versions of Android.

I tried running the tests for jeromq and had 1 failure for tag v0.3.5:

```
Test set: org.zeromq.TestZMQ
-------------------------------------------------------------------------------
Tests run: 17, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.781 sec <<< FAILURE! - in org.zeromq.TestZMQ
testEventDisconnected(org.zeromq.TestZMQ)  Time elapsed: 0.149 sec  <<< FAILURE!
java.lang.AssertionError: No event was received
  at org.junit.Assert.fail(Assert.java:88)
  at org.junit.Assert.assertTrue(Assert.java:41)
  at org.junit.Assert.assertNotNull(Assert.java:621)
  at org.zeromq.TestZMQ.testEventDisconnected(TestZMQ.java:414)
```

And 1 failure for tag v0.3.6:

```
Test set: org.zeromq.TestZMQ
-------------------------------------------------------------------------------
Tests run: 19, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 3.945 sec <<< FAILURE! - in org.zeromq.TestZMQ
testEventDisconnected(org.zeromq.TestZMQ)  Time elapsed: 0.15 sec  <<< FAILURE!
java.lang.AssertionError: No event was received
  at org.junit.Assert.fail(Assert.java:88)
  at org.junit.Assert.assertTrue(Assert.java:41)
  at org.junit.Assert.assertNotNull(Assert.java:621)
  at org.zeromq.TestZMQ.testEventDisconnected(TestZMQ.java:495)

-------------------------------------------------------------------------------
Test set: org.zeromq.TestZProxy
-------------------------------------------------------------------------------
Tests run: 9, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.697 sec <<< FAILURE! - in org.zeromq.TestZProxy
testAllOptionsSyncNewHot(org.zeromq.TestZProxy)  Time elapsed: 0.239 sec  <<< FAILURE!
org.junit.ComparisonFailure: sync status is not good! expected:<[STOPP]ED> but was:<[EXIT]ED>
    at org.junit.Assert.assertEquals(Assert.java:115)
    at org.zeromq.TestZProxy.testAllOptionsSync(TestZProxy.java:275)
    at org.zeromq.TestZProxy.testAllOptionsSyncNewHot(TestZProxy.java:57)
```

I'm not sure if these results have any relation to the issue that I'm having, but I figured that I'd include them. I apologize if I'm missing anything obvious. I've used ZMQ a bit, but I'm not that familiar with Java.

**Comment by daveyarwood** [comment] 2016-10-31 01:33
Could the problem be that you're binding the PULL socket and connecting the PUSH socket?

In the [zguide PUSH/PULL example](http://zguide.zeromq.org/page:all#toc14), they bind the PUSH socket and connect the PULL socket. There is a little explanation there about why this makes sense -- "workers" (with PULL sockets) can come and go, but the ventilator (i.e. PUSH socket) is the stable component, so it should be the bound part.

**Comment by danielunderwood** [comment] 2016-10-31 01:49
I just tried swapping which was bound and which connected and ended up with the same result. But it looks like the task worker in that example actually connects both its PULL and PUSH socket since each worker also has a PUSH socket to send to a sink.

**Comment by daveyarwood** [comment] 2016-10-31 01:58
> But it looks like the task worker in that example actually connects both its PULL and PUSH socket since each worker also has a PUSH socket to send to a sink.

Ah, that's an interesting observation. So I guess that suggests it should work either way.

**Comment by daveyarwood** [comment] 2016-10-31 02:02
One thing to try might be sleeping for longer in the main thread, and see if the PULL thread gets the messages then. This is a shot in the dark, but perhaps what's happening is that 2 seconds isn't long enough for the PULL socket to bind, so by the time it's ready to receive messages, the PUSH socket has already sent all its messages and there is nothing left to receive.

**Comment by danielunderwood** [comment] 2016-10-31 17:05
So with the existing sleeps, it doesn't matter how long I wait. But I found out that if I put a sleep for as little as 10ms after sending the messages from the PUSH and before destroying the PUSH socket, the PULL socket will receive the messages.

So then I have the code
```
        for(int i = 0; i < 20; ++i){
            sock.send(Integer.toString(i));
        }

        try {
            Thread.sleep(10);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }

        ctx.destroySocket(sock);
        ctx.destroy();

```

Is this what the behavior should be or should `destroySocket()` block until the socket has sent all queued messages? Is there any way to check if the socket has outgoing messages queued? I thought using `setLinger()` would change the behavior, but that didn't seem to affect anything. I think the best solution for me will probably be to synchronize the PUSH/PULL setup with a ROUTER/DEALER or REQ/REP, but would be interested to know if other options are available and if this is the intended behavior.

**Comment by daveyarwood** [comment] 2016-10-31 20:04
It seems to me like this is the expected behavior if linger is set to 0, which means "don't wait for any pending actions, just stop what you're doing."

If linger is set to some number of milliseconds, then it should block for that number of milliseconds. If it doesn't, then that seems like a bug.

I could be wrong, though -- I'm somewhat new to this project.

**Comment by danielunderwood** [comment] 2016-10-31 21:11
I noticed that `socketBase.setSocketOpt(ZMQ.ZMQ_LINGER, 0);` is called at at `ManagedContext.java:58`, which sets the linger to 0 before closing the socket. This seems a bit weird, but I also wasn't able to follow the code through every step since I'm not that familiar with ZMQ's reaping process at the moment.

**Comment by daveyarwood** [comment] 2016-10-31 21:32
That does seem weird -- maybe a bug there? cc: @trevorbernard 

On the other hand, it looks like ManagedContext is only used if you use [ZSockets](https://github.com/zeromq/jeromq/blob/master/src/main/java/org/zeromq/ZSocket.java), which are an alternative to creating a ZContext or a ZMQ.Context and using it to make sockets.

**Comment by danielunderwood** [comment] 2016-11-02 21:54
I wasn't aware of the difference with `ZContext` using a `ManagedContext`. I'm not sure if it matters, but using `ZSocket`s seems to result in the same behavior. There is no way to set the `ZSocket` linger as far as I can tell though.

**Comment by danielunderwood** [comment] 2016-11-24 01:11
I tested this with libzmq using [this code](https://gist.github.com/danielunderwood/4239ad86f753682714e87bfdd43a1c55). It seems that regardless of the time that I wait in the puller or the number of messages I send, the puller receives all of the messages. Notice that I haven't set the socket linger or anything like that.

This seems to indicate that JeroMQ has different behavior than libzmq in this case, which I would imagine to be a bad thing.

**Comment by fredoboulo** [comment] 2017-02-22 19:11
did you try to set options on the push socket ?
            push.setDelayAttachOnConnect(true);
that will help to block the sending until a worker is connected.
Little can be done regarding the issue with destroySocket(): Closing straight away the socket/context after sending a message leaves very few chance for the I/O threads to actually send it on the wire.

**Comment by fredoboulo** [comment] 2017-02-22 19:13
I can propose an alternative for your test case:
`
public class TestPushPullBLockingOnSendIfDelayAttachOnConnectIsEnabled
{
    private static final String ADDR = "tcp://*:9988";
    private static final String POISON_PILL = "END";

    public class PullRunnable implements Runnable
    {
        private volatile boolean running = true;

        @Override
        public void run()
        {
            // Sleep to show the blocking of message sending
            // when there is no pull socket
            try {
                Thread.sleep(2000);
            }
            catch (InterruptedException e) {
                e.printStackTrace();
            }

            // Bind socket
            ZContext ctx = new ZContext();
            Socket pullSock = ctx.createSocket(ZMQ.PULL);
            pullSock.bind(ADDR);

            // Receive in a loop
            String response;
            while (running) {
                // Try to receive. Break on ZMQException (socket terminated)
                try {
                    response = pullSock.recvStr();
                    System.out.println("Event received:\t" + response);
                    if (POISON_PILL.equals(response)) {
                        break;
                    }
                }
                catch (org.zeromq.ZMQException ex) {
                    break;
                }
            }

            // Destroy context, which will destroy sockets
            ctx.close();
        }
    }

    @Test
    public void testPushPull() throws Exception
    {
        // Create and start thread for PULL socket
        PullRunnable pullRunnable = new PullRunnable();
        Thread pullThread = new Thread(pullRunnable);
        pullThread.start();

        // Create context and socket for PUSH
        ZContext ctx = new ZContext();
        ZMQ.Socket sock = ctx.createSocket(ZMQ.PUSH);

        // uncomment this line to block the sending of messages
        // until one peer is available
        sock.setDelayAttachOnConnect(true);

        sock.connect(ADDR);

        // Send messages
        // sock.send() should block if not connected
        // to a PULL socket as per the docs
        long start = System.currentTimeMillis();
        for (int i = 0; i < 20; ++i) {
            sock.send(Integer.toString(i));
            long end = System.currentTimeMillis();
            System.out.println((end - start) + ": Sent message #" + i);
        }
        sock.send(POISON_PILL);

        // join Pull process
        try {
            pullThread.join();
        }
        catch (Exception e) {
            e.printStackTrace();
        }
        ctx.close();
    }
}

`

**Comment by danielunderwood** [comment] 2017-02-22 21:19
@fredoboulo I haven't been using JeroMQ lately and have changed my architecture to use PUB/SUB instead of PUSH/PULL, so this isn't a huge issue for me at the moment. You did mention `push.setDelayAttachOnConnect(true);`. I wasn't aware of this socket option and it could very well have fixed my issue. Is this option present in vanilla ZMQ?

**Comment by danielunderwood** [comment] 2017-02-22 22:33
And if that option is something that isn't in libzmq, should it be set on
by default since my code with libzmq resulted in a different behavior?

**Comment by fredoboulo** [comment] 2017-04-02 08:21
@danielunderwood , yes this option is present as well in vanilla ZMQ. 
According to the specs, the push socket shall block on sending : https://rfc.zeromq.org/spec:30/PIPELINE, but this is not achieved by default in the current implementation, you have to manually set the "delay attach on connect" option (AFAIK, this is aligned with zmq 3.x)

**Comment by daveyarwood** [comment] 2018-10-28 01:35
If I'm understanding correctly, I think we've established that JeroMQ is aligned with ZMQ here, and I'm not sure that there is an issue. Please correct me if I'm wrong, and feel free to reopen the issue.

**Closed by daveyarwood** 2018-10-28 01:35 UTC
